// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"zapfs/proto/manager_pb"

	mock "github.com/stretchr/testify/mock"
)

// NewMockManagerClient creates a new instance of MockManagerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerClient {
	mock := &MockManagerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagerClient is an autogenerated mock type for the ManagerClient type
type MockManagerClient struct {
	mock.Mock
}

type MockManagerClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerClient) EXPECT() *MockManagerClient_Expecter {
	return &MockManagerClient_Expecter{mock: &_m.Mock}
}

// GetCollection provides a mock function for the type MockManagerClient
func (_mock *MockManagerClient) GetCollection(ctx context.Context, req *manager_pb.GetCollectionRequest) (*manager_pb.GetCollectionResponse, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 *manager_pb.GetCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetCollectionRequest) (*manager_pb.GetCollectionResponse, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetCollectionRequest) *manager_pb.GetCollectionResponse); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.GetCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.GetCollectionRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerClient_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockManagerClient_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - req *manager_pb.GetCollectionRequest
func (_e *MockManagerClient_Expecter) GetCollection(ctx interface{}, req interface{}) *MockManagerClient_GetCollection_Call {
	return &MockManagerClient_GetCollection_Call{Call: _e.mock.On("GetCollection", ctx, req)}
}

func (_c *MockManagerClient_GetCollection_Call) Run(run func(ctx context.Context, req *manager_pb.GetCollectionRequest)) *MockManagerClient_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.GetCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.GetCollectionRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagerClient_GetCollection_Call) Return(getCollectionResponse *manager_pb.GetCollectionResponse, err error) *MockManagerClient_GetCollection_Call {
	_c.Call.Return(getCollectionResponse, err)
	return _c
}

func (_c *MockManagerClient_GetCollection_Call) RunAndReturn(run func(ctx context.Context, req *manager_pb.GetCollectionRequest) (*manager_pb.GetCollectionResponse, error)) *MockManagerClient_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockManagerClient
func (_mock *MockManagerClient) ListCollections(ctx context.Context, req *manager_pb.ListCollectionsRequest) (manager_pb.ManagerService_ListCollectionsClient, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 manager_pb.ManagerService_ListCollectionsClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.ListCollectionsRequest) (manager_pb.ManagerService_ListCollectionsClient, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.ListCollectionsRequest) manager_pb.ManagerService_ListCollectionsClient); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(manager_pb.ManagerService_ListCollectionsClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.ListCollectionsRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerClient_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockManagerClient_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - ctx context.Context
//   - req *manager_pb.ListCollectionsRequest
func (_e *MockManagerClient_Expecter) ListCollections(ctx interface{}, req interface{}) *MockManagerClient_ListCollections_Call {
	return &MockManagerClient_ListCollections_Call{Call: _e.mock.On("ListCollections", ctx, req)}
}

func (_c *MockManagerClient_ListCollections_Call) Run(run func(ctx context.Context, req *manager_pb.ListCollectionsRequest)) *MockManagerClient_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.ListCollectionsRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.ListCollectionsRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockManagerClient_ListCollections_Call) Return(managerService_ListCollectionsClient manager_pb.ManagerService_ListCollectionsClient, err error) *MockManagerClient_ListCollections_Call {
	_c.Call.Return(managerService_ListCollectionsClient, err)
	return _c
}

func (_c *MockManagerClient_ListCollections_Call) RunAndReturn(run func(ctx context.Context, req *manager_pb.ListCollectionsRequest) (manager_pb.ManagerService_ListCollectionsClient, error)) *MockManagerClient_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}
