// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: file.proto

package file_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FileService_Ping_FullMethodName                   = "/file_pb.FileService/Ping"
	FileService_FileServerStatus_FullMethodName       = "/file_pb.FileService/FileServerStatus"
	FileService_MarkBackendReadOnly_FullMethodName    = "/file_pb.FileService/MarkBackendReadOnly"
	FileService_MarkBackendWritable_FullMethodName    = "/file_pb.FileService/MarkBackendWritable"
	FileService_PutObject_FullMethodName              = "/file_pb.FileService/PutObject"
	FileService_GetObject_FullMethodName              = "/file_pb.FileService/GetObject"
	FileService_GetObjectRange_FullMethodName         = "/file_pb.FileService/GetObjectRange"
	FileService_DeleteObject_FullMethodName           = "/file_pb.FileService/DeleteObject"
	FileService_BatchDeleteObjects_FullMethodName     = "/file_pb.FileService/BatchDeleteObjects"
	FileService_DecrementRefCount_FullMethodName      = "/file_pb.FileService/DecrementRefCount"
	FileService_DecrementRefCountBatch_FullMethodName = "/file_pb.FileService/DecrementRefCountBatch"
	FileService_MigrateChunk_FullMethodName           = "/file_pb.FileService/MigrateChunk"
	FileService_ReceiveChunk_FullMethodName           = "/file_pb.FileService/ReceiveChunk"
	FileService_GetChunk_FullMethodName               = "/file_pb.FileService/GetChunk"
	FileService_ListLocalChunks_FullMethodName        = "/file_pb.FileService/ListLocalChunks"
	FileService_GetLocalChunk_FullMethodName          = "/file_pb.FileService/GetLocalChunk"
	FileService_DeleteLocalChunk_FullMethodName       = "/file_pb.FileService/DeleteLocalChunk"
)

// FileServiceClient is the client API for FileService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FileServiceClient interface {
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	FileServerStatus(ctx context.Context, in *FileServerStatusRequest, opts ...grpc.CallOption) (*FileServerStatusResponse, error)
	MarkBackendReadOnly(ctx context.Context, in *MarkBackendReadOnlyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	MarkBackendWritable(ctx context.Context, in *MarkBackendWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
	PutObject(ctx context.Context, opts ...grpc.CallOption) (FileService_PutObjectClient, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (FileService_GetObjectClient, error)
	GetObjectRange(ctx context.Context, in *GetObjectRangeRequest, opts ...grpc.CallOption) (FileService_GetObjectRangeClient, error)
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	BatchDeleteObjects(ctx context.Context, in *BatchDeleteObjectsRequest, opts ...grpc.CallOption) (*BatchDeleteObjectsResponse, error)
	// RefCount management for GC
	DecrementRefCount(ctx context.Context, in *DecrementRefCountRequest, opts ...grpc.CallOption) (*DecrementRefCountResponse, error)
	DecrementRefCountBatch(ctx context.Context, in *DecrementRefCountBatchRequest, opts ...grpc.CallOption) (*DecrementRefCountBatchResponse, error)
	// Chunk migration for cluster rebalancing
	// MigrateChunk transfers a chunk to a target server (called by manager or admin)
	MigrateChunk(ctx context.Context, in *MigrateChunkRequest, opts ...grpc.CallOption) (*MigrateChunkResponse, error)
	// ReceiveChunk receives a chunk from a peer file server (peer-to-peer transfer)
	ReceiveChunk(ctx context.Context, opts ...grpc.CallOption) (FileService_ReceiveChunkClient, error)
	// GetChunk retrieves raw chunk data by ID (used for migration)
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (FileService_GetChunkClient, error)
	// Debug RPCs for testing and diagnostics
	ListLocalChunks(ctx context.Context, in *ListLocalChunksRequest, opts ...grpc.CallOption) (FileService_ListLocalChunksClient, error)
	GetLocalChunk(ctx context.Context, in *GetLocalChunkRequest, opts ...grpc.CallOption) (*LocalChunkInfo, error)
	DeleteLocalChunk(ctx context.Context, in *DeleteLocalChunkRequest, opts ...grpc.CallOption) (*DeleteLocalChunkResponse, error)
}

type fileServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFileServiceClient(cc grpc.ClientConnInterface) FileServiceClient {
	return &fileServiceClient{cc}
}

func (c *fileServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, FileService_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) FileServerStatus(ctx context.Context, in *FileServerStatusRequest, opts ...grpc.CallOption) (*FileServerStatusResponse, error) {
	out := new(FileServerStatusResponse)
	err := c.cc.Invoke(ctx, FileService_FileServerStatus_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MarkBackendReadOnly(ctx context.Context, in *MarkBackendReadOnlyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FileService_MarkBackendReadOnly_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MarkBackendWritable(ctx context.Context, in *MarkBackendWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, FileService_MarkBackendWritable_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) PutObject(ctx context.Context, opts ...grpc.CallOption) (FileService_PutObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[0], FileService_PutObject_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServicePutObjectClient{stream}
	return x, nil
}

type FileService_PutObjectClient interface {
	Send(*PutObjectRequest) error
	CloseAndRecv() (*PutObjectResponse, error)
	grpc.ClientStream
}

type fileServicePutObjectClient struct {
	grpc.ClientStream
}

func (x *fileServicePutObjectClient) Send(m *PutObjectRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileServicePutObjectClient) CloseAndRecv() (*PutObjectResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(PutObjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (FileService_GetObjectClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[1], FileService_GetObject_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceGetObjectClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileService_GetObjectClient interface {
	Recv() (*GetObjectResponse, error)
	grpc.ClientStream
}

type fileServiceGetObjectClient struct {
	grpc.ClientStream
}

func (x *fileServiceGetObjectClient) Recv() (*GetObjectResponse, error) {
	m := new(GetObjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) GetObjectRange(ctx context.Context, in *GetObjectRangeRequest, opts ...grpc.CallOption) (FileService_GetObjectRangeClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[2], FileService_GetObjectRange_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceGetObjectRangeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileService_GetObjectRangeClient interface {
	Recv() (*GetObjectResponse, error)
	grpc.ClientStream
}

type fileServiceGetObjectRangeClient struct {
	grpc.ClientStream
}

func (x *fileServiceGetObjectRangeClient) Recv() (*GetObjectResponse, error) {
	m := new(GetObjectResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteObject_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) BatchDeleteObjects(ctx context.Context, in *BatchDeleteObjectsRequest, opts ...grpc.CallOption) (*BatchDeleteObjectsResponse, error) {
	out := new(BatchDeleteObjectsResponse)
	err := c.cc.Invoke(ctx, FileService_BatchDeleteObjects_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DecrementRefCount(ctx context.Context, in *DecrementRefCountRequest, opts ...grpc.CallOption) (*DecrementRefCountResponse, error) {
	out := new(DecrementRefCountResponse)
	err := c.cc.Invoke(ctx, FileService_DecrementRefCount_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DecrementRefCountBatch(ctx context.Context, in *DecrementRefCountBatchRequest, opts ...grpc.CallOption) (*DecrementRefCountBatchResponse, error) {
	out := new(DecrementRefCountBatchResponse)
	err := c.cc.Invoke(ctx, FileService_DecrementRefCountBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) MigrateChunk(ctx context.Context, in *MigrateChunkRequest, opts ...grpc.CallOption) (*MigrateChunkResponse, error) {
	out := new(MigrateChunkResponse)
	err := c.cc.Invoke(ctx, FileService_MigrateChunk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) ReceiveChunk(ctx context.Context, opts ...grpc.CallOption) (FileService_ReceiveChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[3], FileService_ReceiveChunk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceReceiveChunkClient{stream}
	return x, nil
}

type FileService_ReceiveChunkClient interface {
	Send(*ReceiveChunkRequest) error
	CloseAndRecv() (*ReceiveChunkResponse, error)
	grpc.ClientStream
}

type fileServiceReceiveChunkClient struct {
	grpc.ClientStream
}

func (x *fileServiceReceiveChunkClient) Send(m *ReceiveChunkRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fileServiceReceiveChunkClient) CloseAndRecv() (*ReceiveChunkResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(ReceiveChunkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (FileService_GetChunkClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[4], FileService_GetChunk_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceGetChunkClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileService_GetChunkClient interface {
	Recv() (*GetChunkResponse, error)
	grpc.ClientStream
}

type fileServiceGetChunkClient struct {
	grpc.ClientStream
}

func (x *fileServiceGetChunkClient) Recv() (*GetChunkResponse, error) {
	m := new(GetChunkResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) ListLocalChunks(ctx context.Context, in *ListLocalChunksRequest, opts ...grpc.CallOption) (FileService_ListLocalChunksClient, error) {
	stream, err := c.cc.NewStream(ctx, &FileService_ServiceDesc.Streams[5], FileService_ListLocalChunks_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fileServiceListLocalChunksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type FileService_ListLocalChunksClient interface {
	Recv() (*LocalChunkInfo, error)
	grpc.ClientStream
}

type fileServiceListLocalChunksClient struct {
	grpc.ClientStream
}

func (x *fileServiceListLocalChunksClient) Recv() (*LocalChunkInfo, error) {
	m := new(LocalChunkInfo)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *fileServiceClient) GetLocalChunk(ctx context.Context, in *GetLocalChunkRequest, opts ...grpc.CallOption) (*LocalChunkInfo, error) {
	out := new(LocalChunkInfo)
	err := c.cc.Invoke(ctx, FileService_GetLocalChunk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fileServiceClient) DeleteLocalChunk(ctx context.Context, in *DeleteLocalChunkRequest, opts ...grpc.CallOption) (*DeleteLocalChunkResponse, error) {
	out := new(DeleteLocalChunkResponse)
	err := c.cc.Invoke(ctx, FileService_DeleteLocalChunk_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FileServiceServer is the server API for FileService service.
// All implementations must embed UnimplementedFileServiceServer
// for forward compatibility
type FileServiceServer interface {
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	FileServerStatus(context.Context, *FileServerStatusRequest) (*FileServerStatusResponse, error)
	MarkBackendReadOnly(context.Context, *MarkBackendReadOnlyRequest) (*emptypb.Empty, error)
	MarkBackendWritable(context.Context, *MarkBackendWritableRequest) (*emptypb.Empty, error)
	PutObject(FileService_PutObjectServer) error
	GetObject(*GetObjectRequest, FileService_GetObjectServer) error
	GetObjectRange(*GetObjectRangeRequest, FileService_GetObjectRangeServer) error
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	BatchDeleteObjects(context.Context, *BatchDeleteObjectsRequest) (*BatchDeleteObjectsResponse, error)
	// RefCount management for GC
	DecrementRefCount(context.Context, *DecrementRefCountRequest) (*DecrementRefCountResponse, error)
	DecrementRefCountBatch(context.Context, *DecrementRefCountBatchRequest) (*DecrementRefCountBatchResponse, error)
	// Chunk migration for cluster rebalancing
	// MigrateChunk transfers a chunk to a target server (called by manager or admin)
	MigrateChunk(context.Context, *MigrateChunkRequest) (*MigrateChunkResponse, error)
	// ReceiveChunk receives a chunk from a peer file server (peer-to-peer transfer)
	ReceiveChunk(FileService_ReceiveChunkServer) error
	// GetChunk retrieves raw chunk data by ID (used for migration)
	GetChunk(*GetChunkRequest, FileService_GetChunkServer) error
	// Debug RPCs for testing and diagnostics
	ListLocalChunks(*ListLocalChunksRequest, FileService_ListLocalChunksServer) error
	GetLocalChunk(context.Context, *GetLocalChunkRequest) (*LocalChunkInfo, error)
	DeleteLocalChunk(context.Context, *DeleteLocalChunkRequest) (*DeleteLocalChunkResponse, error)
	mustEmbedUnimplementedFileServiceServer()
}

// UnimplementedFileServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFileServiceServer struct {
}

func (UnimplementedFileServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedFileServiceServer) FileServerStatus(context.Context, *FileServerStatusRequest) (*FileServerStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FileServerStatus not implemented")
}
func (UnimplementedFileServiceServer) MarkBackendReadOnly(context.Context, *MarkBackendReadOnlyRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBackendReadOnly not implemented")
}
func (UnimplementedFileServiceServer) MarkBackendWritable(context.Context, *MarkBackendWritableRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkBackendWritable not implemented")
}
func (UnimplementedFileServiceServer) PutObject(FileService_PutObjectServer) error {
	return status.Errorf(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedFileServiceServer) GetObject(*GetObjectRequest, FileService_GetObjectServer) error {
	return status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedFileServiceServer) GetObjectRange(*GetObjectRangeRequest, FileService_GetObjectRangeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetObjectRange not implemented")
}
func (UnimplementedFileServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedFileServiceServer) BatchDeleteObjects(context.Context, *BatchDeleteObjectsRequest) (*BatchDeleteObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchDeleteObjects not implemented")
}
func (UnimplementedFileServiceServer) DecrementRefCount(context.Context, *DecrementRefCountRequest) (*DecrementRefCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementRefCount not implemented")
}
func (UnimplementedFileServiceServer) DecrementRefCountBatch(context.Context, *DecrementRefCountBatchRequest) (*DecrementRefCountBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecrementRefCountBatch not implemented")
}
func (UnimplementedFileServiceServer) MigrateChunk(context.Context, *MigrateChunkRequest) (*MigrateChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MigrateChunk not implemented")
}
func (UnimplementedFileServiceServer) ReceiveChunk(FileService_ReceiveChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method ReceiveChunk not implemented")
}
func (UnimplementedFileServiceServer) GetChunk(*GetChunkRequest, FileService_GetChunkServer) error {
	return status.Errorf(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedFileServiceServer) ListLocalChunks(*ListLocalChunksRequest, FileService_ListLocalChunksServer) error {
	return status.Errorf(codes.Unimplemented, "method ListLocalChunks not implemented")
}
func (UnimplementedFileServiceServer) GetLocalChunk(context.Context, *GetLocalChunkRequest) (*LocalChunkInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLocalChunk not implemented")
}
func (UnimplementedFileServiceServer) DeleteLocalChunk(context.Context, *DeleteLocalChunkRequest) (*DeleteLocalChunkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLocalChunk not implemented")
}
func (UnimplementedFileServiceServer) mustEmbedUnimplementedFileServiceServer() {}

// UnsafeFileServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FileServiceServer will
// result in compilation errors.
type UnsafeFileServiceServer interface {
	mustEmbedUnimplementedFileServiceServer()
}

func RegisterFileServiceServer(s grpc.ServiceRegistrar, srv FileServiceServer) {
	s.RegisterService(&FileService_ServiceDesc, srv)
}

func _FileService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_FileServerStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FileServerStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).FileServerStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_FileServerStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).FileServerStatus(ctx, req.(*FileServerStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MarkBackendReadOnly_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBackendReadOnlyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MarkBackendReadOnly(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MarkBackendReadOnly_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MarkBackendReadOnly(ctx, req.(*MarkBackendReadOnlyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MarkBackendWritable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkBackendWritableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MarkBackendWritable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MarkBackendWritable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MarkBackendWritable(ctx, req.(*MarkBackendWritableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_PutObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).PutObject(&fileServicePutObjectServer{stream})
}

type FileService_PutObjectServer interface {
	SendAndClose(*PutObjectResponse) error
	Recv() (*PutObjectRequest, error)
	grpc.ServerStream
}

type fileServicePutObjectServer struct {
	grpc.ServerStream
}

func (x *fileServicePutObjectServer) SendAndClose(m *PutObjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileServicePutObjectServer) Recv() (*PutObjectRequest, error) {
	m := new(PutObjectRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileService_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).GetObject(m, &fileServiceGetObjectServer{stream})
}

type FileService_GetObjectServer interface {
	Send(*GetObjectResponse) error
	grpc.ServerStream
}

type fileServiceGetObjectServer struct {
	grpc.ServerStream
}

func (x *fileServiceGetObjectServer) Send(m *GetObjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FileService_GetObjectRange_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRangeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).GetObjectRange(m, &fileServiceGetObjectRangeServer{stream})
}

type FileService_GetObjectRangeServer interface {
	Send(*GetObjectResponse) error
	grpc.ServerStream
}

type fileServiceGetObjectRangeServer struct {
	grpc.ServerStream
}

func (x *fileServiceGetObjectRangeServer) Send(m *GetObjectResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FileService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_BatchDeleteObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDeleteObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).BatchDeleteObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_BatchDeleteObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).BatchDeleteObjects(ctx, req.(*BatchDeleteObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DecrementRefCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementRefCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DecrementRefCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DecrementRefCount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DecrementRefCount(ctx, req.(*DecrementRefCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DecrementRefCountBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementRefCountBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DecrementRefCountBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DecrementRefCountBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DecrementRefCountBatch(ctx, req.(*DecrementRefCountBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_MigrateChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrateChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).MigrateChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_MigrateChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).MigrateChunk(ctx, req.(*MigrateChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_ReceiveChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FileServiceServer).ReceiveChunk(&fileServiceReceiveChunkServer{stream})
}

type FileService_ReceiveChunkServer interface {
	SendAndClose(*ReceiveChunkResponse) error
	Recv() (*ReceiveChunkRequest, error)
	grpc.ServerStream
}

type fileServiceReceiveChunkServer struct {
	grpc.ServerStream
}

func (x *fileServiceReceiveChunkServer) SendAndClose(m *ReceiveChunkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fileServiceReceiveChunkServer) Recv() (*ReceiveChunkRequest, error) {
	m := new(ReceiveChunkRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _FileService_GetChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).GetChunk(m, &fileServiceGetChunkServer{stream})
}

type FileService_GetChunkServer interface {
	Send(*GetChunkResponse) error
	grpc.ServerStream
}

type fileServiceGetChunkServer struct {
	grpc.ServerStream
}

func (x *fileServiceGetChunkServer) Send(m *GetChunkResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _FileService_ListLocalChunks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListLocalChunksRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FileServiceServer).ListLocalChunks(m, &fileServiceListLocalChunksServer{stream})
}

type FileService_ListLocalChunksServer interface {
	Send(*LocalChunkInfo) error
	grpc.ServerStream
}

type fileServiceListLocalChunksServer struct {
	grpc.ServerStream
}

func (x *fileServiceListLocalChunksServer) Send(m *LocalChunkInfo) error {
	return x.ServerStream.SendMsg(m)
}

func _FileService_GetLocalChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLocalChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).GetLocalChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_GetLocalChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).GetLocalChunk(ctx, req.(*GetLocalChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FileService_DeleteLocalChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLocalChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FileServiceServer).DeleteLocalChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FileService_DeleteLocalChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FileServiceServer).DeleteLocalChunk(ctx, req.(*DeleteLocalChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FileService_ServiceDesc is the grpc.ServiceDesc for FileService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FileService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "file_pb.FileService",
	HandlerType: (*FileServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _FileService_Ping_Handler,
		},
		{
			MethodName: "FileServerStatus",
			Handler:    _FileService_FileServerStatus_Handler,
		},
		{
			MethodName: "MarkBackendReadOnly",
			Handler:    _FileService_MarkBackendReadOnly_Handler,
		},
		{
			MethodName: "MarkBackendWritable",
			Handler:    _FileService_MarkBackendWritable_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _FileService_DeleteObject_Handler,
		},
		{
			MethodName: "BatchDeleteObjects",
			Handler:    _FileService_BatchDeleteObjects_Handler,
		},
		{
			MethodName: "DecrementRefCount",
			Handler:    _FileService_DecrementRefCount_Handler,
		},
		{
			MethodName: "DecrementRefCountBatch",
			Handler:    _FileService_DecrementRefCountBatch_Handler,
		},
		{
			MethodName: "MigrateChunk",
			Handler:    _FileService_MigrateChunk_Handler,
		},
		{
			MethodName: "GetLocalChunk",
			Handler:    _FileService_GetLocalChunk_Handler,
		},
		{
			MethodName: "DeleteLocalChunk",
			Handler:    _FileService_DeleteLocalChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutObject",
			Handler:       _FileService_PutObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _FileService_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetObjectRange",
			Handler:       _FileService_GetObjectRange_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReceiveChunk",
			Handler:       _FileService_ReceiveChunk_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetChunk",
			Handler:       _FileService_GetChunk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListLocalChunks",
			Handler:       _FileService_ListLocalChunks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "file.proto",
}
