// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/proto/file_pb"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
	"google.golang.org/protobuf/types/known/emptypb"
)

// NewMockFileServiceClient creates a new instance of MockFileServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileServiceClient {
	mock := &MockFileServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileServiceClient is an autogenerated mock type for the FileServiceClient type
type MockFileServiceClient struct {
	mock.Mock
}

type MockFileServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileServiceClient) EXPECT() *MockFileServiceClient_Expecter {
	return &MockFileServiceClient_Expecter{mock: &_m.Mock}
}

// BatchDeleteObjects provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) BatchDeleteObjects(ctx context.Context, in *file_pb.BatchDeleteObjectsRequest, opts ...grpc.CallOption) (*file_pb.BatchDeleteObjectsResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for BatchDeleteObjects")
	}

	var r0 *file_pb.BatchDeleteObjectsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.BatchDeleteObjectsRequest, ...grpc.CallOption) (*file_pb.BatchDeleteObjectsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.BatchDeleteObjectsRequest, ...grpc.CallOption) *file_pb.BatchDeleteObjectsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.BatchDeleteObjectsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.BatchDeleteObjectsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_BatchDeleteObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchDeleteObjects'
type MockFileServiceClient_BatchDeleteObjects_Call struct {
	*mock.Call
}

// BatchDeleteObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.BatchDeleteObjectsRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) BatchDeleteObjects(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_BatchDeleteObjects_Call {
	return &MockFileServiceClient_BatchDeleteObjects_Call{Call: _e.mock.On("BatchDeleteObjects",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_BatchDeleteObjects_Call) Run(run func(ctx context.Context, in *file_pb.BatchDeleteObjectsRequest, opts ...grpc.CallOption)) *MockFileServiceClient_BatchDeleteObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.BatchDeleteObjectsRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.BatchDeleteObjectsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_BatchDeleteObjects_Call) Return(batchDeleteObjectsResponse *file_pb.BatchDeleteObjectsResponse, err error) *MockFileServiceClient_BatchDeleteObjects_Call {
	_c.Call.Return(batchDeleteObjectsResponse, err)
	return _c
}

func (_c *MockFileServiceClient_BatchDeleteObjects_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.BatchDeleteObjectsRequest, opts ...grpc.CallOption) (*file_pb.BatchDeleteObjectsResponse, error)) *MockFileServiceClient_BatchDeleteObjects_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRefCount provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) DecrementRefCount(ctx context.Context, in *file_pb.DecrementRefCountRequest, opts ...grpc.CallOption) (*file_pb.DecrementRefCountResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRefCount")
	}

	var r0 *file_pb.DecrementRefCountResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DecrementRefCountRequest, ...grpc.CallOption) (*file_pb.DecrementRefCountResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DecrementRefCountRequest, ...grpc.CallOption) *file_pb.DecrementRefCountResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.DecrementRefCountResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.DecrementRefCountRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_DecrementRefCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRefCount'
type MockFileServiceClient_DecrementRefCount_Call struct {
	*mock.Call
}

// DecrementRefCount is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.DecrementRefCountRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) DecrementRefCount(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_DecrementRefCount_Call {
	return &MockFileServiceClient_DecrementRefCount_Call{Call: _e.mock.On("DecrementRefCount",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_DecrementRefCount_Call) Run(run func(ctx context.Context, in *file_pb.DecrementRefCountRequest, opts ...grpc.CallOption)) *MockFileServiceClient_DecrementRefCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.DecrementRefCountRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.DecrementRefCountRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_DecrementRefCount_Call) Return(decrementRefCountResponse *file_pb.DecrementRefCountResponse, err error) *MockFileServiceClient_DecrementRefCount_Call {
	_c.Call.Return(decrementRefCountResponse, err)
	return _c
}

func (_c *MockFileServiceClient_DecrementRefCount_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.DecrementRefCountRequest, opts ...grpc.CallOption) (*file_pb.DecrementRefCountResponse, error)) *MockFileServiceClient_DecrementRefCount_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRefCountBatch provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) DecrementRefCountBatch(ctx context.Context, in *file_pb.DecrementRefCountBatchRequest, opts ...grpc.CallOption) (*file_pb.DecrementRefCountBatchResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRefCountBatch")
	}

	var r0 *file_pb.DecrementRefCountBatchResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DecrementRefCountBatchRequest, ...grpc.CallOption) (*file_pb.DecrementRefCountBatchResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DecrementRefCountBatchRequest, ...grpc.CallOption) *file_pb.DecrementRefCountBatchResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.DecrementRefCountBatchResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.DecrementRefCountBatchRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_DecrementRefCountBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRefCountBatch'
type MockFileServiceClient_DecrementRefCountBatch_Call struct {
	*mock.Call
}

// DecrementRefCountBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.DecrementRefCountBatchRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) DecrementRefCountBatch(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_DecrementRefCountBatch_Call {
	return &MockFileServiceClient_DecrementRefCountBatch_Call{Call: _e.mock.On("DecrementRefCountBatch",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_DecrementRefCountBatch_Call) Run(run func(ctx context.Context, in *file_pb.DecrementRefCountBatchRequest, opts ...grpc.CallOption)) *MockFileServiceClient_DecrementRefCountBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.DecrementRefCountBatchRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.DecrementRefCountBatchRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_DecrementRefCountBatch_Call) Return(decrementRefCountBatchResponse *file_pb.DecrementRefCountBatchResponse, err error) *MockFileServiceClient_DecrementRefCountBatch_Call {
	_c.Call.Return(decrementRefCountBatchResponse, err)
	return _c
}

func (_c *MockFileServiceClient_DecrementRefCountBatch_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.DecrementRefCountBatchRequest, opts ...grpc.CallOption) (*file_pb.DecrementRefCountBatchResponse, error)) *MockFileServiceClient_DecrementRefCountBatch_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) DeleteObject(ctx context.Context, in *file_pb.DeleteObjectRequest, opts ...grpc.CallOption) (*file_pb.DeleteObjectResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *file_pb.DeleteObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DeleteObjectRequest, ...grpc.CallOption) (*file_pb.DeleteObjectResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.DeleteObjectRequest, ...grpc.CallOption) *file_pb.DeleteObjectResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.DeleteObjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.DeleteObjectRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockFileServiceClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.DeleteObjectRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) DeleteObject(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_DeleteObject_Call {
	return &MockFileServiceClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_DeleteObject_Call) Run(run func(ctx context.Context, in *file_pb.DeleteObjectRequest, opts ...grpc.CallOption)) *MockFileServiceClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.DeleteObjectRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.DeleteObjectRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_DeleteObject_Call) Return(deleteObjectResponse *file_pb.DeleteObjectResponse, err error) *MockFileServiceClient_DeleteObject_Call {
	_c.Call.Return(deleteObjectResponse, err)
	return _c
}

func (_c *MockFileServiceClient_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.DeleteObjectRequest, opts ...grpc.CallOption) (*file_pb.DeleteObjectResponse, error)) *MockFileServiceClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// FileServerStatus provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) FileServerStatus(ctx context.Context, in *file_pb.FileServerStatusRequest, opts ...grpc.CallOption) (*file_pb.FileServerStatusResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for FileServerStatus")
	}

	var r0 *file_pb.FileServerStatusResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.FileServerStatusRequest, ...grpc.CallOption) (*file_pb.FileServerStatusResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.FileServerStatusRequest, ...grpc.CallOption) *file_pb.FileServerStatusResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.FileServerStatusResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.FileServerStatusRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_FileServerStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FileServerStatus'
type MockFileServiceClient_FileServerStatus_Call struct {
	*mock.Call
}

// FileServerStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.FileServerStatusRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) FileServerStatus(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_FileServerStatus_Call {
	return &MockFileServiceClient_FileServerStatus_Call{Call: _e.mock.On("FileServerStatus",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_FileServerStatus_Call) Run(run func(ctx context.Context, in *file_pb.FileServerStatusRequest, opts ...grpc.CallOption)) *MockFileServiceClient_FileServerStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.FileServerStatusRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.FileServerStatusRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_FileServerStatus_Call) Return(fileServerStatusResponse *file_pb.FileServerStatusResponse, err error) *MockFileServiceClient_FileServerStatus_Call {
	_c.Call.Return(fileServerStatusResponse, err)
	return _c
}

func (_c *MockFileServiceClient_FileServerStatus_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.FileServerStatusRequest, opts ...grpc.CallOption) (*file_pb.FileServerStatusResponse, error)) *MockFileServiceClient_FileServerStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) GetObject(ctx context.Context, in *file_pb.GetObjectRequest, opts ...grpc.CallOption) (file_pb.FileService_GetObjectClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 file_pb.FileService_GetObjectClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.GetObjectRequest, ...grpc.CallOption) (file_pb.FileService_GetObjectClient, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.GetObjectRequest, ...grpc.CallOption) file_pb.FileService_GetObjectClient); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(file_pb.FileService_GetObjectClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.GetObjectRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockFileServiceClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.GetObjectRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) GetObject(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_GetObject_Call {
	return &MockFileServiceClient_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_GetObject_Call) Run(run func(ctx context.Context, in *file_pb.GetObjectRequest, opts ...grpc.CallOption)) *MockFileServiceClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.GetObjectRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.GetObjectRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_GetObject_Call) Return(fileService_GetObjectClient file_pb.FileService_GetObjectClient, err error) *MockFileServiceClient_GetObject_Call {
	_c.Call.Return(fileService_GetObjectClient, err)
	return _c
}

func (_c *MockFileServiceClient_GetObject_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.GetObjectRequest, opts ...grpc.CallOption) (file_pb.FileService_GetObjectClient, error)) *MockFileServiceClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectRange provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) GetObjectRange(ctx context.Context, in *file_pb.GetObjectRangeRequest, opts ...grpc.CallOption) (file_pb.FileService_GetObjectRangeClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectRange")
	}

	var r0 file_pb.FileService_GetObjectRangeClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.GetObjectRangeRequest, ...grpc.CallOption) (file_pb.FileService_GetObjectRangeClient, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.GetObjectRangeRequest, ...grpc.CallOption) file_pb.FileService_GetObjectRangeClient); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(file_pb.FileService_GetObjectRangeClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.GetObjectRangeRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_GetObjectRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectRange'
type MockFileServiceClient_GetObjectRange_Call struct {
	*mock.Call
}

// GetObjectRange is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.GetObjectRangeRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) GetObjectRange(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_GetObjectRange_Call {
	return &MockFileServiceClient_GetObjectRange_Call{Call: _e.mock.On("GetObjectRange",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_GetObjectRange_Call) Run(run func(ctx context.Context, in *file_pb.GetObjectRangeRequest, opts ...grpc.CallOption)) *MockFileServiceClient_GetObjectRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.GetObjectRangeRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.GetObjectRangeRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_GetObjectRange_Call) Return(fileService_GetObjectRangeClient file_pb.FileService_GetObjectRangeClient, err error) *MockFileServiceClient_GetObjectRange_Call {
	_c.Call.Return(fileService_GetObjectRangeClient, err)
	return _c
}

func (_c *MockFileServiceClient_GetObjectRange_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.GetObjectRangeRequest, opts ...grpc.CallOption) (file_pb.FileService_GetObjectRangeClient, error)) *MockFileServiceClient_GetObjectRange_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBackendReadOnly provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) MarkBackendReadOnly(ctx context.Context, in *file_pb.MarkBackendReadOnlyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MarkBackendReadOnly")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.MarkBackendReadOnlyRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.MarkBackendReadOnlyRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.MarkBackendReadOnlyRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_MarkBackendReadOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBackendReadOnly'
type MockFileServiceClient_MarkBackendReadOnly_Call struct {
	*mock.Call
}

// MarkBackendReadOnly is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.MarkBackendReadOnlyRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) MarkBackendReadOnly(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_MarkBackendReadOnly_Call {
	return &MockFileServiceClient_MarkBackendReadOnly_Call{Call: _e.mock.On("MarkBackendReadOnly",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_MarkBackendReadOnly_Call) Run(run func(ctx context.Context, in *file_pb.MarkBackendReadOnlyRequest, opts ...grpc.CallOption)) *MockFileServiceClient_MarkBackendReadOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.MarkBackendReadOnlyRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.MarkBackendReadOnlyRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_MarkBackendReadOnly_Call) Return(empty *emptypb.Empty, err error) *MockFileServiceClient_MarkBackendReadOnly_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockFileServiceClient_MarkBackendReadOnly_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.MarkBackendReadOnlyRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)) *MockFileServiceClient_MarkBackendReadOnly_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBackendWritable provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) MarkBackendWritable(ctx context.Context, in *file_pb.MarkBackendWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for MarkBackendWritable")
	}

	var r0 *emptypb.Empty
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.MarkBackendWritableRequest, ...grpc.CallOption) (*emptypb.Empty, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.MarkBackendWritableRequest, ...grpc.CallOption) *emptypb.Empty); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*emptypb.Empty)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.MarkBackendWritableRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_MarkBackendWritable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBackendWritable'
type MockFileServiceClient_MarkBackendWritable_Call struct {
	*mock.Call
}

// MarkBackendWritable is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.MarkBackendWritableRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) MarkBackendWritable(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_MarkBackendWritable_Call {
	return &MockFileServiceClient_MarkBackendWritable_Call{Call: _e.mock.On("MarkBackendWritable",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_MarkBackendWritable_Call) Run(run func(ctx context.Context, in *file_pb.MarkBackendWritableRequest, opts ...grpc.CallOption)) *MockFileServiceClient_MarkBackendWritable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.MarkBackendWritableRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.MarkBackendWritableRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_MarkBackendWritable_Call) Return(empty *emptypb.Empty, err error) *MockFileServiceClient_MarkBackendWritable_Call {
	_c.Call.Return(empty, err)
	return _c
}

func (_c *MockFileServiceClient_MarkBackendWritable_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.MarkBackendWritableRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)) *MockFileServiceClient_MarkBackendWritable_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) Ping(ctx context.Context, in *file_pb.PingRequest, opts ...grpc.CallOption) (*file_pb.PingResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *file_pb.PingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.PingRequest, ...grpc.CallOption) (*file_pb.PingResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *file_pb.PingRequest, ...grpc.CallOption) *file_pb.PingResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*file_pb.PingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *file_pb.PingRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockFileServiceClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *file_pb.PingRequest
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockFileServiceClient_Ping_Call {
	return &MockFileServiceClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockFileServiceClient_Ping_Call) Run(run func(ctx context.Context, in *file_pb.PingRequest, opts ...grpc.CallOption)) *MockFileServiceClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *file_pb.PingRequest
		if args[1] != nil {
			arg1 = args[1].(*file_pb.PingRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_Ping_Call) Return(pingResponse *file_pb.PingResponse, err error) *MockFileServiceClient_Ping_Call {
	_c.Call.Return(pingResponse, err)
	return _c
}

func (_c *MockFileServiceClient_Ping_Call) RunAndReturn(run func(ctx context.Context, in *file_pb.PingRequest, opts ...grpc.CallOption) (*file_pb.PingResponse, error)) *MockFileServiceClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockFileServiceClient
func (_mock *MockFileServiceClient) PutObject(ctx context.Context, opts ...grpc.CallOption) (file_pb.FileService_PutObjectClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 file_pb.FileService_PutObjectClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) (file_pb.FileService_PutObjectClient, error)); ok {
		return returnFunc(ctx, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...grpc.CallOption) file_pb.FileService_PutObjectClient); ok {
		r0 = returnFunc(ctx, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(file_pb.FileService_PutObjectClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileServiceClient_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockFileServiceClient_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - opts ...grpc.CallOption
func (_e *MockFileServiceClient_Expecter) PutObject(ctx interface{}, opts ...interface{}) *MockFileServiceClient_PutObject_Call {
	return &MockFileServiceClient_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx}, opts...)...)}
}

func (_c *MockFileServiceClient_PutObject_Call) Run(run func(ctx context.Context, opts ...grpc.CallOption)) *MockFileServiceClient_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockFileServiceClient_PutObject_Call) Return(fileService_PutObjectClient file_pb.FileService_PutObjectClient, err error) *MockFileServiceClient_PutObject_Call {
	_c.Call.Return(fileService_PutObjectClient, err)
	return _c
}

func (_c *MockFileServiceClient_PutObject_Call) RunAndReturn(run func(ctx context.Context, opts ...grpc.CallOption) (file_pb.FileService_PutObjectClient, error)) *MockFileServiceClient_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
