// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"zapfs/pkg/metadata/service/storage"
	"zapfs/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockStorage creates a new instance of MockStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorage {
	mock := &MockStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorage is an autogenerated mock type for the Storage type
type MockStorage struct {
	mock.Mock
}

type MockStorage_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorage) EXPECT() *MockStorage_Expecter {
	return &MockStorage_Expecter{mock: &_m.Mock}
}

// DecrementChunkRefCounts provides a mock function for the type MockStorage
func (_mock *MockStorage) DecrementChunkRefCounts(ctx context.Context, chunks []types.ChunkRef) []storage.FailedDecrement {
	ret := _mock.Called(ctx, chunks)

	if len(ret) == 0 {
		panic("no return value specified for DecrementChunkRefCounts")
	}

	var r0 []storage.FailedDecrement
	if returnFunc, ok := ret.Get(0).(func(context.Context, []types.ChunkRef) []storage.FailedDecrement); ok {
		r0 = returnFunc(ctx, chunks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]storage.FailedDecrement)
		}
	}
	return r0
}

// MockStorage_DecrementChunkRefCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementChunkRefCounts'
type MockStorage_DecrementChunkRefCounts_Call struct {
	*mock.Call
}

// DecrementChunkRefCounts is a helper method to define mock.On call
//   - ctx context.Context
//   - chunks []types.ChunkRef
func (_e *MockStorage_Expecter) DecrementChunkRefCounts(ctx interface{}, chunks interface{}) *MockStorage_DecrementChunkRefCounts_Call {
	return &MockStorage_DecrementChunkRefCounts_Call{Call: _e.mock.On("DecrementChunkRefCounts", ctx, chunks)}
}

func (_c *MockStorage_DecrementChunkRefCounts_Call) Run(run func(ctx context.Context, chunks []types.ChunkRef)) *MockStorage_DecrementChunkRefCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []types.ChunkRef
		if args[1] != nil {
			arg1 = args[1].([]types.ChunkRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_DecrementChunkRefCounts_Call) Return(failedDecrements []storage.FailedDecrement) *MockStorage_DecrementChunkRefCounts_Call {
	_c.Call.Return(failedDecrements)
	return _c
}

func (_c *MockStorage_DecrementChunkRefCounts_Call) RunAndReturn(run func(ctx context.Context, chunks []types.ChunkRef) []storage.FailedDecrement) *MockStorage_DecrementChunkRefCounts_Call {
	_c.Call.Return(run)
	return _c
}

// WriteObject provides a mock function for the type MockStorage
func (_mock *MockStorage) WriteObject(ctx context.Context, req *storage.WriteRequest) (*storage.WriteResult, error) {
	ret := _mock.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for WriteObject")
	}

	var r0 *storage.WriteResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.WriteRequest) (*storage.WriteResult, error)); ok {
		return returnFunc(ctx, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *storage.WriteRequest) *storage.WriteResult); ok {
		r0 = returnFunc(ctx, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.WriteResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *storage.WriteRequest) error); ok {
		r1 = returnFunc(ctx, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorage_WriteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteObject'
type MockStorage_WriteObject_Call struct {
	*mock.Call
}

// WriteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - req *storage.WriteRequest
func (_e *MockStorage_Expecter) WriteObject(ctx interface{}, req interface{}) *MockStorage_WriteObject_Call {
	return &MockStorage_WriteObject_Call{Call: _e.mock.On("WriteObject", ctx, req)}
}

func (_c *MockStorage_WriteObject_Call) Run(run func(ctx context.Context, req *storage.WriteRequest)) *MockStorage_WriteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *storage.WriteRequest
		if args[1] != nil {
			arg1 = args[1].(*storage.WriteRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorage_WriteObject_Call) Return(writeResult *storage.WriteResult, err error) *MockStorage_WriteObject_Call {
	_c.Call.Return(writeResult, err)
	return _c
}

func (_c *MockStorage_WriteObject_Call) RunAndReturn(run func(ctx context.Context, req *storage.WriteRequest) (*storage.WriteResult, error)) *MockStorage_WriteObject_Call {
	_c.Call.Return(run)
	return _c
}
