// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/pkg/s3api/s3types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEncryptionStore creates a new instance of MockEncryptionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncryptionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncryptionStore {
	mock := &MockEncryptionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEncryptionStore is an autogenerated mock type for the EncryptionStore type
type MockEncryptionStore struct {
	mock.Mock
}

type MockEncryptionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncryptionStore) EXPECT() *MockEncryptionStore_Expecter {
	return &MockEncryptionStore_Expecter{mock: &_m.Mock}
}

// DeleteBucketEncryption provides a mock function for the type MockEncryptionStore
func (_mock *MockEncryptionStore) DeleteBucketEncryption(ctx context.Context, bucket string) error {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucketEncryption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEncryptionStore_DeleteBucketEncryption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucketEncryption'
type MockEncryptionStore_DeleteBucketEncryption_Call struct {
	*mock.Call
}

// DeleteBucketEncryption is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockEncryptionStore_Expecter) DeleteBucketEncryption(ctx interface{}, bucket interface{}) *MockEncryptionStore_DeleteBucketEncryption_Call {
	return &MockEncryptionStore_DeleteBucketEncryption_Call{Call: _e.mock.On("DeleteBucketEncryption", ctx, bucket)}
}

func (_c *MockEncryptionStore_DeleteBucketEncryption_Call) Run(run func(ctx context.Context, bucket string)) *MockEncryptionStore_DeleteBucketEncryption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEncryptionStore_DeleteBucketEncryption_Call) Return(err error) *MockEncryptionStore_DeleteBucketEncryption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEncryptionStore_DeleteBucketEncryption_Call) RunAndReturn(run func(ctx context.Context, bucket string) error) *MockEncryptionStore_DeleteBucketEncryption_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketEncryption provides a mock function for the type MockEncryptionStore
func (_mock *MockEncryptionStore) GetBucketEncryption(ctx context.Context, bucket string) (*s3types.ServerSideEncryptionConfig, error) {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketEncryption")
	}

	var r0 *s3types.ServerSideEncryptionConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*s3types.ServerSideEncryptionConfig, error)); ok {
		return returnFunc(ctx, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *s3types.ServerSideEncryptionConfig); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.ServerSideEncryptionConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEncryptionStore_GetBucketEncryption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketEncryption'
type MockEncryptionStore_GetBucketEncryption_Call struct {
	*mock.Call
}

// GetBucketEncryption is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockEncryptionStore_Expecter) GetBucketEncryption(ctx interface{}, bucket interface{}) *MockEncryptionStore_GetBucketEncryption_Call {
	return &MockEncryptionStore_GetBucketEncryption_Call{Call: _e.mock.On("GetBucketEncryption", ctx, bucket)}
}

func (_c *MockEncryptionStore_GetBucketEncryption_Call) Run(run func(ctx context.Context, bucket string)) *MockEncryptionStore_GetBucketEncryption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEncryptionStore_GetBucketEncryption_Call) Return(serverSideEncryptionConfig *s3types.ServerSideEncryptionConfig, err error) *MockEncryptionStore_GetBucketEncryption_Call {
	_c.Call.Return(serverSideEncryptionConfig, err)
	return _c
}

func (_c *MockEncryptionStore_GetBucketEncryption_Call) RunAndReturn(run func(ctx context.Context, bucket string) (*s3types.ServerSideEncryptionConfig, error)) *MockEncryptionStore_GetBucketEncryption_Call {
	_c.Call.Return(run)
	return _c
}

// SetBucketEncryption provides a mock function for the type MockEncryptionStore
func (_mock *MockEncryptionStore) SetBucketEncryption(ctx context.Context, bucket string, config *s3types.ServerSideEncryptionConfig) error {
	ret := _mock.Called(ctx, bucket, config)

	if len(ret) == 0 {
		panic("no return value specified for SetBucketEncryption")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *s3types.ServerSideEncryptionConfig) error); ok {
		r0 = returnFunc(ctx, bucket, config)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEncryptionStore_SetBucketEncryption_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBucketEncryption'
type MockEncryptionStore_SetBucketEncryption_Call struct {
	*mock.Call
}

// SetBucketEncryption is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - config *s3types.ServerSideEncryptionConfig
func (_e *MockEncryptionStore_Expecter) SetBucketEncryption(ctx interface{}, bucket interface{}, config interface{}) *MockEncryptionStore_SetBucketEncryption_Call {
	return &MockEncryptionStore_SetBucketEncryption_Call{Call: _e.mock.On("SetBucketEncryption", ctx, bucket, config)}
}

func (_c *MockEncryptionStore_SetBucketEncryption_Call) Run(run func(ctx context.Context, bucket string, config *s3types.ServerSideEncryptionConfig)) *MockEncryptionStore_SetBucketEncryption_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *s3types.ServerSideEncryptionConfig
		if args[2] != nil {
			arg2 = args[2].(*s3types.ServerSideEncryptionConfig)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEncryptionStore_SetBucketEncryption_Call) Return(err error) *MockEncryptionStore_SetBucketEncryption_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEncryptionStore_SetBucketEncryption_Call) RunAndReturn(run func(ctx context.Context, bucket string, config *s3types.ServerSideEncryptionConfig) error) *MockEncryptionStore_SetBucketEncryption_Call {
	_c.Call.Return(run)
	return _c
}
