// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/pkg/metadata/db"
	"github.com/LeeDigitalWorks/zapfs/pkg/types"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockObjectStore creates a new instance of MockObjectStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockObjectStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockObjectStore {
	mock := &MockObjectStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockObjectStore is an autogenerated mock type for the ObjectStore type
type MockObjectStore struct {
	mock.Mock
}

type MockObjectStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockObjectStore) EXPECT() *MockObjectStore_Expecter {
	return &MockObjectStore_Expecter{mock: &_m.Mock}
}

// DeleteObject provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) DeleteObject(ctx context.Context, bucket string, key string) error {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockObjectStore_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockObjectStore_Expecter) DeleteObject(ctx interface{}, bucket interface{}, key interface{}) *MockObjectStore_DeleteObject_Call {
	return &MockObjectStore_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, bucket, key)}
}

func (_c *MockObjectStore_DeleteObject_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockObjectStore_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectStore_DeleteObject_Call) Return(err error) *MockObjectStore_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) error) *MockObjectStore_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) GetObject(ctx context.Context, bucket string, key string) (*types.ObjectRef, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *types.ObjectRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*types.ObjectRef, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *types.ObjectRef); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ObjectRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockObjectStore_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockObjectStore_Expecter) GetObject(ctx interface{}, bucket interface{}, key interface{}) *MockObjectStore_GetObject_Call {
	return &MockObjectStore_GetObject_Call{Call: _e.mock.On("GetObject", ctx, bucket, key)}
}

func (_c *MockObjectStore_GetObject_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockObjectStore_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectStore_GetObject_Call) Return(objectRef *types.ObjectRef, err error) *MockObjectStore_GetObject_Call {
	_c.Call.Return(objectRef, err)
	return _c
}

func (_c *MockObjectStore_GetObject_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (*types.ObjectRef, error)) *MockObjectStore_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectByID provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) GetObjectByID(ctx context.Context, id uuid.UUID) (*types.ObjectRef, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectByID")
	}

	var r0 *types.ObjectRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*types.ObjectRef, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *types.ObjectRef); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ObjectRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_GetObjectByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectByID'
type MockObjectStore_GetObjectByID_Call struct {
	*mock.Call
}

// GetObjectByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockObjectStore_Expecter) GetObjectByID(ctx interface{}, id interface{}) *MockObjectStore_GetObjectByID_Call {
	return &MockObjectStore_GetObjectByID_Call{Call: _e.mock.On("GetObjectByID", ctx, id)}
}

func (_c *MockObjectStore_GetObjectByID_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockObjectStore_GetObjectByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_GetObjectByID_Call) Return(objectRef *types.ObjectRef, err error) *MockObjectStore_GetObjectByID_Call {
	_c.Call.Return(objectRef, err)
	return _c
}

func (_c *MockObjectStore_GetObjectByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID) (*types.ObjectRef, error)) *MockObjectStore_GetObjectByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDeletedObjects provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) ListDeletedObjects(ctx context.Context, olderThan int64, limit int) ([]*types.ObjectRef, error) {
	ret := _mock.Called(ctx, olderThan, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListDeletedObjects")
	}

	var r0 []*types.ObjectRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) ([]*types.ObjectRef, error)); ok {
		return returnFunc(ctx, olderThan, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int64, int) []*types.ObjectRef); ok {
		r0 = returnFunc(ctx, olderThan, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.ObjectRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int64, int) error); ok {
		r1 = returnFunc(ctx, olderThan, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_ListDeletedObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDeletedObjects'
type MockObjectStore_ListDeletedObjects_Call struct {
	*mock.Call
}

// ListDeletedObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan int64
//   - limit int
func (_e *MockObjectStore_Expecter) ListDeletedObjects(ctx interface{}, olderThan interface{}, limit interface{}) *MockObjectStore_ListDeletedObjects_Call {
	return &MockObjectStore_ListDeletedObjects_Call{Call: _e.mock.On("ListDeletedObjects", ctx, olderThan, limit)}
}

func (_c *MockObjectStore_ListDeletedObjects_Call) Run(run func(ctx context.Context, olderThan int64, limit int)) *MockObjectStore_ListDeletedObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int64
		if args[1] != nil {
			arg1 = args[1].(int64)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockObjectStore_ListDeletedObjects_Call) Return(objectRefs []*types.ObjectRef, err error) *MockObjectStore_ListDeletedObjects_Call {
	_c.Call.Return(objectRefs, err)
	return _c
}

func (_c *MockObjectStore_ListDeletedObjects_Call) RunAndReturn(run func(ctx context.Context, olderThan int64, limit int) ([]*types.ObjectRef, error)) *MockObjectStore_ListDeletedObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) ListObjects(ctx context.Context, bucket string, prefix string, limit int) ([]*types.ObjectRef, error) {
	ret := _mock.Called(ctx, bucket, prefix, limit)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 []*types.ObjectRef
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) ([]*types.ObjectRef, error)); ok {
		return returnFunc(ctx, bucket, prefix, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int) []*types.ObjectRef); ok {
		r0 = returnFunc(ctx, bucket, prefix, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.ObjectRef)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int) error); ok {
		r1 = returnFunc(ctx, bucket, prefix, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockObjectStore_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix string
//   - limit int
func (_e *MockObjectStore_Expecter) ListObjects(ctx interface{}, bucket interface{}, prefix interface{}, limit interface{}) *MockObjectStore_ListObjects_Call {
	return &MockObjectStore_ListObjects_Call{Call: _e.mock.On("ListObjects", ctx, bucket, prefix, limit)}
}

func (_c *MockObjectStore_ListObjects_Call) Run(run func(ctx context.Context, bucket string, prefix string, limit int)) *MockObjectStore_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockObjectStore_ListObjects_Call) Return(objectRefs []*types.ObjectRef, err error) *MockObjectStore_ListObjects_Call {
	_c.Call.Return(objectRefs, err)
	return _c
}

func (_c *MockObjectStore_ListObjects_Call) RunAndReturn(run func(ctx context.Context, bucket string, prefix string, limit int) ([]*types.ObjectRef, error)) *MockObjectStore_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) ListObjectsV2(ctx context.Context, params *db.ListObjectsParams) (*db.ListObjectsResult, error) {
	ret := _mock.Called(ctx, params)

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *db.ListObjectsResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.ListObjectsParams) (*db.ListObjectsResult, error)); ok {
		return returnFunc(ctx, params)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.ListObjectsParams) *db.ListObjectsResult); ok {
		r0 = returnFunc(ctx, params)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.ListObjectsResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.ListObjectsParams) error); ok {
		r1 = returnFunc(ctx, params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockObjectStore_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type MockObjectStore_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - params *db.ListObjectsParams
func (_e *MockObjectStore_Expecter) ListObjectsV2(ctx interface{}, params interface{}) *MockObjectStore_ListObjectsV2_Call {
	return &MockObjectStore_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2", ctx, params)}
}

func (_c *MockObjectStore_ListObjectsV2_Call) Run(run func(ctx context.Context, params *db.ListObjectsParams)) *MockObjectStore_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.ListObjectsParams
		if args[1] != nil {
			arg1 = args[1].(*db.ListObjectsParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_ListObjectsV2_Call) Return(listObjectsResult *db.ListObjectsResult, err error) *MockObjectStore_ListObjectsV2_Call {
	_c.Call.Return(listObjectsResult, err)
	return _c
}

func (_c *MockObjectStore_ListObjectsV2_Call) RunAndReturn(run func(ctx context.Context, params *db.ListObjectsParams) (*db.ListObjectsResult, error)) *MockObjectStore_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// MarkObjectDeleted provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) MarkObjectDeleted(ctx context.Context, bucket string, key string, deletedAt int64) error {
	ret := _mock.Called(ctx, bucket, key, deletedAt)

	if len(ret) == 0 {
		panic("no return value specified for MarkObjectDeleted")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = returnFunc(ctx, bucket, key, deletedAt)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_MarkObjectDeleted_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkObjectDeleted'
type MockObjectStore_MarkObjectDeleted_Call struct {
	*mock.Call
}

// MarkObjectDeleted is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - deletedAt int64
func (_e *MockObjectStore_Expecter) MarkObjectDeleted(ctx interface{}, bucket interface{}, key interface{}, deletedAt interface{}) *MockObjectStore_MarkObjectDeleted_Call {
	return &MockObjectStore_MarkObjectDeleted_Call{Call: _e.mock.On("MarkObjectDeleted", ctx, bucket, key, deletedAt)}
}

func (_c *MockObjectStore_MarkObjectDeleted_Call) Run(run func(ctx context.Context, bucket string, key string, deletedAt int64)) *MockObjectStore_MarkObjectDeleted_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockObjectStore_MarkObjectDeleted_Call) Return(err error) *MockObjectStore_MarkObjectDeleted_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_MarkObjectDeleted_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, deletedAt int64) error) *MockObjectStore_MarkObjectDeleted_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockObjectStore
func (_mock *MockObjectStore) PutObject(ctx context.Context, obj *types.ObjectRef) error {
	ret := _mock.Called(ctx, obj)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.ObjectRef) error); ok {
		r0 = returnFunc(ctx, obj)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockObjectStore_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockObjectStore_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - obj *types.ObjectRef
func (_e *MockObjectStore_Expecter) PutObject(ctx interface{}, obj interface{}) *MockObjectStore_PutObject_Call {
	return &MockObjectStore_PutObject_Call{Call: _e.mock.On("PutObject", ctx, obj)}
}

func (_c *MockObjectStore_PutObject_Call) Run(run func(ctx context.Context, obj *types.ObjectRef)) *MockObjectStore_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.ObjectRef
		if args[1] != nil {
			arg1 = args[1].(*types.ObjectRef)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockObjectStore_PutObject_Call) Return(err error) *MockObjectStore_PutObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockObjectStore_PutObject_Call) RunAndReturn(run func(ctx context.Context, obj *types.ObjectRef) error) *MockObjectStore_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
