// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"zapfs/pkg/s3api/s3types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockTaggingStore creates a new instance of MockTaggingStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTaggingStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTaggingStore {
	mock := &MockTaggingStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTaggingStore is an autogenerated mock type for the TaggingStore type
type MockTaggingStore struct {
	mock.Mock
}

type MockTaggingStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTaggingStore) EXPECT() *MockTaggingStore_Expecter {
	return &MockTaggingStore_Expecter{mock: &_m.Mock}
}

// DeleteBucketTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) DeleteBucketTagging(ctx context.Context, bucket string) error {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucketTagging")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaggingStore_DeleteBucketTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucketTagging'
type MockTaggingStore_DeleteBucketTagging_Call struct {
	*mock.Call
}

// DeleteBucketTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockTaggingStore_Expecter) DeleteBucketTagging(ctx interface{}, bucket interface{}) *MockTaggingStore_DeleteBucketTagging_Call {
	return &MockTaggingStore_DeleteBucketTagging_Call{Call: _e.mock.On("DeleteBucketTagging", ctx, bucket)}
}

func (_c *MockTaggingStore_DeleteBucketTagging_Call) Run(run func(ctx context.Context, bucket string)) *MockTaggingStore_DeleteBucketTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaggingStore_DeleteBucketTagging_Call) Return(err error) *MockTaggingStore_DeleteBucketTagging_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaggingStore_DeleteBucketTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string) error) *MockTaggingStore_DeleteBucketTagging_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObjectTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) DeleteObjectTagging(ctx context.Context, bucket string, key string) error {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObjectTagging")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaggingStore_DeleteObjectTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObjectTagging'
type MockTaggingStore_DeleteObjectTagging_Call struct {
	*mock.Call
}

// DeleteObjectTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockTaggingStore_Expecter) DeleteObjectTagging(ctx interface{}, bucket interface{}, key interface{}) *MockTaggingStore_DeleteObjectTagging_Call {
	return &MockTaggingStore_DeleteObjectTagging_Call{Call: _e.mock.On("DeleteObjectTagging", ctx, bucket, key)}
}

func (_c *MockTaggingStore_DeleteObjectTagging_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockTaggingStore_DeleteObjectTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaggingStore_DeleteObjectTagging_Call) Return(err error) *MockTaggingStore_DeleteObjectTagging_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaggingStore_DeleteObjectTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) error) *MockTaggingStore_DeleteObjectTagging_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) GetBucketTagging(ctx context.Context, bucket string) (*s3types.TagSet, error) {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketTagging")
	}

	var r0 *s3types.TagSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*s3types.TagSet, error)); ok {
		return returnFunc(ctx, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *s3types.TagSet); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.TagSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaggingStore_GetBucketTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketTagging'
type MockTaggingStore_GetBucketTagging_Call struct {
	*mock.Call
}

// GetBucketTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockTaggingStore_Expecter) GetBucketTagging(ctx interface{}, bucket interface{}) *MockTaggingStore_GetBucketTagging_Call {
	return &MockTaggingStore_GetBucketTagging_Call{Call: _e.mock.On("GetBucketTagging", ctx, bucket)}
}

func (_c *MockTaggingStore_GetBucketTagging_Call) Run(run func(ctx context.Context, bucket string)) *MockTaggingStore_GetBucketTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTaggingStore_GetBucketTagging_Call) Return(tagSet *s3types.TagSet, err error) *MockTaggingStore_GetBucketTagging_Call {
	_c.Call.Return(tagSet, err)
	return _c
}

func (_c *MockTaggingStore_GetBucketTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string) (*s3types.TagSet, error)) *MockTaggingStore_GetBucketTagging_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) GetObjectTagging(ctx context.Context, bucket string, key string) (*s3types.TagSet, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectTagging")
	}

	var r0 *s3types.TagSet
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*s3types.TagSet, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *s3types.TagSet); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.TagSet)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockTaggingStore_GetObjectTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectTagging'
type MockTaggingStore_GetObjectTagging_Call struct {
	*mock.Call
}

// GetObjectTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockTaggingStore_Expecter) GetObjectTagging(ctx interface{}, bucket interface{}, key interface{}) *MockTaggingStore_GetObjectTagging_Call {
	return &MockTaggingStore_GetObjectTagging_Call{Call: _e.mock.On("GetObjectTagging", ctx, bucket, key)}
}

func (_c *MockTaggingStore_GetObjectTagging_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockTaggingStore_GetObjectTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaggingStore_GetObjectTagging_Call) Return(tagSet *s3types.TagSet, err error) *MockTaggingStore_GetObjectTagging_Call {
	_c.Call.Return(tagSet, err)
	return _c
}

func (_c *MockTaggingStore_GetObjectTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (*s3types.TagSet, error)) *MockTaggingStore_GetObjectTagging_Call {
	_c.Call.Return(run)
	return _c
}

// SetBucketTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) SetBucketTagging(ctx context.Context, bucket string, tagSet *s3types.TagSet) error {
	ret := _mock.Called(ctx, bucket, tagSet)

	if len(ret) == 0 {
		panic("no return value specified for SetBucketTagging")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *s3types.TagSet) error); ok {
		r0 = returnFunc(ctx, bucket, tagSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaggingStore_SetBucketTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBucketTagging'
type MockTaggingStore_SetBucketTagging_Call struct {
	*mock.Call
}

// SetBucketTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - tagSet *s3types.TagSet
func (_e *MockTaggingStore_Expecter) SetBucketTagging(ctx interface{}, bucket interface{}, tagSet interface{}) *MockTaggingStore_SetBucketTagging_Call {
	return &MockTaggingStore_SetBucketTagging_Call{Call: _e.mock.On("SetBucketTagging", ctx, bucket, tagSet)}
}

func (_c *MockTaggingStore_SetBucketTagging_Call) Run(run func(ctx context.Context, bucket string, tagSet *s3types.TagSet)) *MockTaggingStore_SetBucketTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *s3types.TagSet
		if args[2] != nil {
			arg2 = args[2].(*s3types.TagSet)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockTaggingStore_SetBucketTagging_Call) Return(err error) *MockTaggingStore_SetBucketTagging_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaggingStore_SetBucketTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string, tagSet *s3types.TagSet) error) *MockTaggingStore_SetBucketTagging_Call {
	_c.Call.Return(run)
	return _c
}

// SetObjectTagging provides a mock function for the type MockTaggingStore
func (_mock *MockTaggingStore) SetObjectTagging(ctx context.Context, bucket string, key string, tagSet *s3types.TagSet) error {
	ret := _mock.Called(ctx, bucket, key, tagSet)

	if len(ret) == 0 {
		panic("no return value specified for SetObjectTagging")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *s3types.TagSet) error); ok {
		r0 = returnFunc(ctx, bucket, key, tagSet)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTaggingStore_SetObjectTagging_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetObjectTagging'
type MockTaggingStore_SetObjectTagging_Call struct {
	*mock.Call
}

// SetObjectTagging is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - tagSet *s3types.TagSet
func (_e *MockTaggingStore_Expecter) SetObjectTagging(ctx interface{}, bucket interface{}, key interface{}, tagSet interface{}) *MockTaggingStore_SetObjectTagging_Call {
	return &MockTaggingStore_SetObjectTagging_Call{Call: _e.mock.On("SetObjectTagging", ctx, bucket, key, tagSet)}
}

func (_c *MockTaggingStore_SetObjectTagging_Call) Run(run func(ctx context.Context, bucket string, key string, tagSet *s3types.TagSet)) *MockTaggingStore_SetObjectTagging_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *s3types.TagSet
		if args[3] != nil {
			arg3 = args[3].(*s3types.TagSet)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockTaggingStore_SetObjectTagging_Call) Return(err error) *MockTaggingStore_SetObjectTagging_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTaggingStore_SetObjectTagging_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, tagSet *s3types.TagSet) error) *MockTaggingStore_SetObjectTagging_Call {
	_c.Call.Return(run)
	return _c
}
