// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/LeeDigitalWorks/zapfs/pkg/types"

	mock "github.com/stretchr/testify/mock"
)

// NewMockMultipartStore creates a new instance of MockMultipartStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMultipartStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMultipartStore {
	mock := &MockMultipartStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMultipartStore is an autogenerated mock type for the MultipartStore type
type MockMultipartStore struct {
	mock.Mock
}

type MockMultipartStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMultipartStore) EXPECT() *MockMultipartStore_Expecter {
	return &MockMultipartStore_Expecter{mock: &_m.Mock}
}

// CreateMultipartUpload provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) CreateMultipartUpload(ctx context.Context, upload *types.MultipartUpload) error {
	ret := _mock.Called(ctx, upload)

	if len(ret) == 0 {
		panic("no return value specified for CreateMultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.MultipartUpload) error); ok {
		r0 = returnFunc(ctx, upload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMultipartStore_CreateMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMultipartUpload'
type MockMultipartStore_CreateMultipartUpload_Call struct {
	*mock.Call
}

// CreateMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - upload *types.MultipartUpload
func (_e *MockMultipartStore_Expecter) CreateMultipartUpload(ctx interface{}, upload interface{}) *MockMultipartStore_CreateMultipartUpload_Call {
	return &MockMultipartStore_CreateMultipartUpload_Call{Call: _e.mock.On("CreateMultipartUpload", ctx, upload)}
}

func (_c *MockMultipartStore_CreateMultipartUpload_Call) Run(run func(ctx context.Context, upload *types.MultipartUpload)) *MockMultipartStore_CreateMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.MultipartUpload
		if args[1] != nil {
			arg1 = args[1].(*types.MultipartUpload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMultipartStore_CreateMultipartUpload_Call) Return(err error) *MockMultipartStore_CreateMultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMultipartStore_CreateMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, upload *types.MultipartUpload) error) *MockMultipartStore_CreateMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMultipartUpload provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) DeleteMultipartUpload(ctx context.Context, bucket string, key string, uploadID string) error {
	ret := _mock.Called(ctx, bucket, key, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = returnFunc(ctx, bucket, key, uploadID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMultipartStore_DeleteMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMultipartUpload'
type MockMultipartStore_DeleteMultipartUpload_Call struct {
	*mock.Call
}

// DeleteMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - uploadID string
func (_e *MockMultipartStore_Expecter) DeleteMultipartUpload(ctx interface{}, bucket interface{}, key interface{}, uploadID interface{}) *MockMultipartStore_DeleteMultipartUpload_Call {
	return &MockMultipartStore_DeleteMultipartUpload_Call{Call: _e.mock.On("DeleteMultipartUpload", ctx, bucket, key, uploadID)}
}

func (_c *MockMultipartStore_DeleteMultipartUpload_Call) Run(run func(ctx context.Context, bucket string, key string, uploadID string)) *MockMultipartStore_DeleteMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMultipartStore_DeleteMultipartUpload_Call) Return(err error) *MockMultipartStore_DeleteMultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMultipartStore_DeleteMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, uploadID string) error) *MockMultipartStore_DeleteMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteParts provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) DeleteParts(ctx context.Context, uploadID string) error {
	ret := _mock.Called(ctx, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParts")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, uploadID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMultipartStore_DeleteParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParts'
type MockMultipartStore_DeleteParts_Call struct {
	*mock.Call
}

// DeleteParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
func (_e *MockMultipartStore_Expecter) DeleteParts(ctx interface{}, uploadID interface{}) *MockMultipartStore_DeleteParts_Call {
	return &MockMultipartStore_DeleteParts_Call{Call: _e.mock.On("DeleteParts", ctx, uploadID)}
}

func (_c *MockMultipartStore_DeleteParts_Call) Run(run func(ctx context.Context, uploadID string)) *MockMultipartStore_DeleteParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMultipartStore_DeleteParts_Call) Return(err error) *MockMultipartStore_DeleteParts_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMultipartStore_DeleteParts_Call) RunAndReturn(run func(ctx context.Context, uploadID string) error) *MockMultipartStore_DeleteParts_Call {
	_c.Call.Return(run)
	return _c
}

// GetMultipartUpload provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) GetMultipartUpload(ctx context.Context, bucket string, key string, uploadID string) (*types.MultipartUpload, error) {
	ret := _mock.Called(ctx, bucket, key, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for GetMultipartUpload")
	}

	var r0 *types.MultipartUpload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*types.MultipartUpload, error)); ok {
		return returnFunc(ctx, bucket, key, uploadID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *types.MultipartUpload); ok {
		r0 = returnFunc(ctx, bucket, key, uploadID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MultipartUpload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key, uploadID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMultipartStore_GetMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMultipartUpload'
type MockMultipartStore_GetMultipartUpload_Call struct {
	*mock.Call
}

// GetMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - uploadID string
func (_e *MockMultipartStore_Expecter) GetMultipartUpload(ctx interface{}, bucket interface{}, key interface{}, uploadID interface{}) *MockMultipartStore_GetMultipartUpload_Call {
	return &MockMultipartStore_GetMultipartUpload_Call{Call: _e.mock.On("GetMultipartUpload", ctx, bucket, key, uploadID)}
}

func (_c *MockMultipartStore_GetMultipartUpload_Call) Run(run func(ctx context.Context, bucket string, key string, uploadID string)) *MockMultipartStore_GetMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMultipartStore_GetMultipartUpload_Call) Return(multipartUpload *types.MultipartUpload, err error) *MockMultipartStore_GetMultipartUpload_Call {
	_c.Call.Return(multipartUpload, err)
	return _c
}

func (_c *MockMultipartStore_GetMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, uploadID string) (*types.MultipartUpload, error)) *MockMultipartStore_GetMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// GetPart provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) GetPart(ctx context.Context, uploadID string, partNumber int) (*types.MultipartPart, error) {
	ret := _mock.Called(ctx, uploadID, partNumber)

	if len(ret) == 0 {
		panic("no return value specified for GetPart")
	}

	var r0 *types.MultipartPart
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) (*types.MultipartPart, error)); ok {
		return returnFunc(ctx, uploadID, partNumber)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) *types.MultipartPart); ok {
		r0 = returnFunc(ctx, uploadID, partNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.MultipartPart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, uploadID, partNumber)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMultipartStore_GetPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPart'
type MockMultipartStore_GetPart_Call struct {
	*mock.Call
}

// GetPart is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - partNumber int
func (_e *MockMultipartStore_Expecter) GetPart(ctx interface{}, uploadID interface{}, partNumber interface{}) *MockMultipartStore_GetPart_Call {
	return &MockMultipartStore_GetPart_Call{Call: _e.mock.On("GetPart", ctx, uploadID, partNumber)}
}

func (_c *MockMultipartStore_GetPart_Call) Run(run func(ctx context.Context, uploadID string, partNumber int)) *MockMultipartStore_GetPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMultipartStore_GetPart_Call) Return(multipartPart *types.MultipartPart, err error) *MockMultipartStore_GetPart_Call {
	_c.Call.Return(multipartPart, err)
	return _c
}

func (_c *MockMultipartStore_GetPart_Call) RunAndReturn(run func(ctx context.Context, uploadID string, partNumber int) (*types.MultipartPart, error)) *MockMultipartStore_GetPart_Call {
	_c.Call.Return(run)
	return _c
}

// ListMultipartUploads provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) ListMultipartUploads(ctx context.Context, bucket string, prefix string, keyMarker string, uploadIDMarker string, maxUploads int) ([]*types.MultipartUpload, bool, error) {
	ret := _mock.Called(ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)

	if len(ret) == 0 {
		panic("no return value specified for ListMultipartUploads")
	}

	var r0 []*types.MultipartUpload
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) ([]*types.MultipartUpload, bool, error)); ok {
		return returnFunc(ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, int) []*types.MultipartUpload); ok {
		r0 = returnFunc(ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.MultipartUpload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, int) bool); ok {
		r1 = returnFunc(ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, string, string, string, int) error); ok {
		r2 = returnFunc(ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMultipartStore_ListMultipartUploads_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMultipartUploads'
type MockMultipartStore_ListMultipartUploads_Call struct {
	*mock.Call
}

// ListMultipartUploads is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - prefix string
//   - keyMarker string
//   - uploadIDMarker string
//   - maxUploads int
func (_e *MockMultipartStore_Expecter) ListMultipartUploads(ctx interface{}, bucket interface{}, prefix interface{}, keyMarker interface{}, uploadIDMarker interface{}, maxUploads interface{}) *MockMultipartStore_ListMultipartUploads_Call {
	return &MockMultipartStore_ListMultipartUploads_Call{Call: _e.mock.On("ListMultipartUploads", ctx, bucket, prefix, keyMarker, uploadIDMarker, maxUploads)}
}

func (_c *MockMultipartStore_ListMultipartUploads_Call) Run(run func(ctx context.Context, bucket string, prefix string, keyMarker string, uploadIDMarker string, maxUploads int)) *MockMultipartStore_ListMultipartUploads_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int
		if args[5] != nil {
			arg5 = args[5].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMultipartStore_ListMultipartUploads_Call) Return(multipartUploads []*types.MultipartUpload, b bool, err error) *MockMultipartStore_ListMultipartUploads_Call {
	_c.Call.Return(multipartUploads, b, err)
	return _c
}

func (_c *MockMultipartStore_ListMultipartUploads_Call) RunAndReturn(run func(ctx context.Context, bucket string, prefix string, keyMarker string, uploadIDMarker string, maxUploads int) ([]*types.MultipartUpload, bool, error)) *MockMultipartStore_ListMultipartUploads_Call {
	_c.Call.Return(run)
	return _c
}

// ListParts provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) ListParts(ctx context.Context, uploadID string, partNumberMarker int, maxParts int) ([]*types.MultipartPart, bool, error) {
	ret := _mock.Called(ctx, uploadID, partNumberMarker, maxParts)

	if len(ret) == 0 {
		panic("no return value specified for ListParts")
	}

	var r0 []*types.MultipartPart
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*types.MultipartPart, bool, error)); ok {
		return returnFunc(ctx, uploadID, partNumberMarker, maxParts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, int) []*types.MultipartPart); ok {
		r0 = returnFunc(ctx, uploadID, partNumberMarker, maxParts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*types.MultipartPart)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, int) bool); ok {
		r1 = returnFunc(ctx, uploadID, partNumberMarker, maxParts)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, int) error); ok {
		r2 = returnFunc(ctx, uploadID, partNumberMarker, maxParts)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMultipartStore_ListParts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListParts'
type MockMultipartStore_ListParts_Call struct {
	*mock.Call
}

// ListParts is a helper method to define mock.On call
//   - ctx context.Context
//   - uploadID string
//   - partNumberMarker int
//   - maxParts int
func (_e *MockMultipartStore_Expecter) ListParts(ctx interface{}, uploadID interface{}, partNumberMarker interface{}, maxParts interface{}) *MockMultipartStore_ListParts_Call {
	return &MockMultipartStore_ListParts_Call{Call: _e.mock.On("ListParts", ctx, uploadID, partNumberMarker, maxParts)}
}

func (_c *MockMultipartStore_ListParts_Call) Run(run func(ctx context.Context, uploadID string, partNumberMarker int, maxParts int)) *MockMultipartStore_ListParts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockMultipartStore_ListParts_Call) Return(multipartParts []*types.MultipartPart, b bool, err error) *MockMultipartStore_ListParts_Call {
	_c.Call.Return(multipartParts, b, err)
	return _c
}

func (_c *MockMultipartStore_ListParts_Call) RunAndReturn(run func(ctx context.Context, uploadID string, partNumberMarker int, maxParts int) ([]*types.MultipartPart, bool, error)) *MockMultipartStore_ListParts_Call {
	_c.Call.Return(run)
	return _c
}

// PutPart provides a mock function for the type MockMultipartStore
func (_mock *MockMultipartStore) PutPart(ctx context.Context, part *types.MultipartPart) error {
	ret := _mock.Called(ctx, part)

	if len(ret) == 0 {
		panic("no return value specified for PutPart")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *types.MultipartPart) error); ok {
		r0 = returnFunc(ctx, part)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMultipartStore_PutPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutPart'
type MockMultipartStore_PutPart_Call struct {
	*mock.Call
}

// PutPart is a helper method to define mock.On call
//   - ctx context.Context
//   - part *types.MultipartPart
func (_e *MockMultipartStore_Expecter) PutPart(ctx interface{}, part interface{}) *MockMultipartStore_PutPart_Call {
	return &MockMultipartStore_PutPart_Call{Call: _e.mock.On("PutPart", ctx, part)}
}

func (_c *MockMultipartStore_PutPart_Call) Run(run func(ctx context.Context, part *types.MultipartPart)) *MockMultipartStore_PutPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *types.MultipartPart
		if args[1] != nil {
			arg1 = args[1].(*types.MultipartPart)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMultipartStore_PutPart_Call) Return(err error) *MockMultipartStore_PutPart_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMultipartStore_PutPart_Call) RunAndReturn(run func(ctx context.Context, part *types.MultipartPart) error) *MockMultipartStore_PutPart_Call {
	_c.Call.Return(run)
	return _c
}
