// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/pkg/s3api/s3types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockACLStore creates a new instance of MockACLStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockACLStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockACLStore {
	mock := &MockACLStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockACLStore is an autogenerated mock type for the ACLStore type
type MockACLStore struct {
	mock.Mock
}

type MockACLStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockACLStore) EXPECT() *MockACLStore_Expecter {
	return &MockACLStore_Expecter{mock: &_m.Mock}
}

// GetBucketACL provides a mock function for the type MockACLStore
func (_mock *MockACLStore) GetBucketACL(ctx context.Context, bucket string) (*s3types.AccessControlList, error) {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketACL")
	}

	var r0 *s3types.AccessControlList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*s3types.AccessControlList, error)); ok {
		return returnFunc(ctx, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *s3types.AccessControlList); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.AccessControlList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, bucket)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLStore_GetBucketACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketACL'
type MockACLStore_GetBucketACL_Call struct {
	*mock.Call
}

// GetBucketACL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockACLStore_Expecter) GetBucketACL(ctx interface{}, bucket interface{}) *MockACLStore_GetBucketACL_Call {
	return &MockACLStore_GetBucketACL_Call{Call: _e.mock.On("GetBucketACL", ctx, bucket)}
}

func (_c *MockACLStore_GetBucketACL_Call) Run(run func(ctx context.Context, bucket string)) *MockACLStore_GetBucketACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockACLStore_GetBucketACL_Call) Return(accessControlList *s3types.AccessControlList, err error) *MockACLStore_GetBucketACL_Call {
	_c.Call.Return(accessControlList, err)
	return _c
}

func (_c *MockACLStore_GetBucketACL_Call) RunAndReturn(run func(ctx context.Context, bucket string) (*s3types.AccessControlList, error)) *MockACLStore_GetBucketACL_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectACL provides a mock function for the type MockACLStore
func (_mock *MockACLStore) GetObjectACL(ctx context.Context, bucket string, key string) (*s3types.AccessControlList, error) {
	ret := _mock.Called(ctx, bucket, key)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectACL")
	}

	var r0 *s3types.AccessControlList
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*s3types.AccessControlList, error)); ok {
		return returnFunc(ctx, bucket, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *s3types.AccessControlList); ok {
		r0 = returnFunc(ctx, bucket, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.AccessControlList)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, bucket, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockACLStore_GetObjectACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectACL'
type MockACLStore_GetObjectACL_Call struct {
	*mock.Call
}

// GetObjectACL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
func (_e *MockACLStore_Expecter) GetObjectACL(ctx interface{}, bucket interface{}, key interface{}) *MockACLStore_GetObjectACL_Call {
	return &MockACLStore_GetObjectACL_Call{Call: _e.mock.On("GetObjectACL", ctx, bucket, key)}
}

func (_c *MockACLStore_GetObjectACL_Call) Run(run func(ctx context.Context, bucket string, key string)) *MockACLStore_GetObjectACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockACLStore_GetObjectACL_Call) Return(accessControlList *s3types.AccessControlList, err error) *MockACLStore_GetObjectACL_Call {
	_c.Call.Return(accessControlList, err)
	return _c
}

func (_c *MockACLStore_GetObjectACL_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string) (*s3types.AccessControlList, error)) *MockACLStore_GetObjectACL_Call {
	_c.Call.Return(run)
	return _c
}

// SetBucketACL provides a mock function for the type MockACLStore
func (_mock *MockACLStore) SetBucketACL(ctx context.Context, bucket string, acl *s3types.AccessControlList) error {
	ret := _mock.Called(ctx, bucket, acl)

	if len(ret) == 0 {
		panic("no return value specified for SetBucketACL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *s3types.AccessControlList) error); ok {
		r0 = returnFunc(ctx, bucket, acl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockACLStore_SetBucketACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBucketACL'
type MockACLStore_SetBucketACL_Call struct {
	*mock.Call
}

// SetBucketACL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - acl *s3types.AccessControlList
func (_e *MockACLStore_Expecter) SetBucketACL(ctx interface{}, bucket interface{}, acl interface{}) *MockACLStore_SetBucketACL_Call {
	return &MockACLStore_SetBucketACL_Call{Call: _e.mock.On("SetBucketACL", ctx, bucket, acl)}
}

func (_c *MockACLStore_SetBucketACL_Call) Run(run func(ctx context.Context, bucket string, acl *s3types.AccessControlList)) *MockACLStore_SetBucketACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *s3types.AccessControlList
		if args[2] != nil {
			arg2 = args[2].(*s3types.AccessControlList)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockACLStore_SetBucketACL_Call) Return(err error) *MockACLStore_SetBucketACL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockACLStore_SetBucketACL_Call) RunAndReturn(run func(ctx context.Context, bucket string, acl *s3types.AccessControlList) error) *MockACLStore_SetBucketACL_Call {
	_c.Call.Return(run)
	return _c
}

// SetObjectACL provides a mock function for the type MockACLStore
func (_mock *MockACLStore) SetObjectACL(ctx context.Context, bucket string, key string, acl *s3types.AccessControlList) error {
	ret := _mock.Called(ctx, bucket, key, acl)

	if len(ret) == 0 {
		panic("no return value specified for SetObjectACL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, *s3types.AccessControlList) error); ok {
		r0 = returnFunc(ctx, bucket, key, acl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockACLStore_SetObjectACL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetObjectACL'
type MockACLStore_SetObjectACL_Call struct {
	*mock.Call
}

// SetObjectACL is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - key string
//   - acl *s3types.AccessControlList
func (_e *MockACLStore_Expecter) SetObjectACL(ctx interface{}, bucket interface{}, key interface{}, acl interface{}) *MockACLStore_SetObjectACL_Call {
	return &MockACLStore_SetObjectACL_Call{Call: _e.mock.On("SetObjectACL", ctx, bucket, key, acl)}
}

func (_c *MockACLStore_SetObjectACL_Call) Run(run func(ctx context.Context, bucket string, key string, acl *s3types.AccessControlList)) *MockACLStore_SetObjectACL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *s3types.AccessControlList
		if args[3] != nil {
			arg3 = args[3].(*s3types.AccessControlList)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockACLStore_SetObjectACL_Call) Return(err error) *MockACLStore_SetObjectACL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockACLStore_SetObjectACL_Call) RunAndReturn(run func(ctx context.Context, bucket string, key string, acl *s3types.AccessControlList) error) *MockACLStore_SetObjectACL_Call {
	_c.Call.Return(run)
	return _c
}
