// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/pkg/s3api/s3types"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBucketStore creates a new instance of MockBucketStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBucketStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBucketStore {
	mock := &MockBucketStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBucketStore is an autogenerated mock type for the BucketStore type
type MockBucketStore struct {
	mock.Mock
}

type MockBucketStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBucketStore) EXPECT() *MockBucketStore_Expecter {
	return &MockBucketStore_Expecter{mock: &_m.Mock}
}

// GetBucket provides a mock function for the type MockBucketStore
func (_mock *MockBucketStore) GetBucket(name string) (s3types.Bucket, bool) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetBucket")
	}

	var r0 s3types.Bucket
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (s3types.Bucket, bool)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) s3types.Bucket); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Get(0).(s3types.Bucket)
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockBucketStore_GetBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucket'
type MockBucketStore_GetBucket_Call struct {
	*mock.Call
}

// GetBucket is a helper method to define mock.On call
//   - name string
func (_e *MockBucketStore_Expecter) GetBucket(name interface{}) *MockBucketStore_GetBucket_Call {
	return &MockBucketStore_GetBucket_Call{Call: _e.mock.On("GetBucket", name)}
}

func (_c *MockBucketStore_GetBucket_Call) Run(run func(name string)) *MockBucketStore_GetBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBucketStore_GetBucket_Call) Return(bucket s3types.Bucket, b bool) *MockBucketStore_GetBucket_Call {
	_c.Call.Return(bucket, b)
	return _c
}

func (_c *MockBucketStore_GetBucket_Call) RunAndReturn(run func(name string) (s3types.Bucket, bool)) *MockBucketStore_GetBucket_Call {
	_c.Call.Return(run)
	return _c
}

// GetBucketPolicy provides a mock function for the type MockBucketStore
func (_mock *MockBucketStore) GetBucketPolicy(ctx context.Context, bucket string) (*s3types.BucketPolicy, bool) {
	ret := _mock.Called(ctx, bucket)

	if len(ret) == 0 {
		panic("no return value specified for GetBucketPolicy")
	}

	var r0 *s3types.BucketPolicy
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*s3types.BucketPolicy, bool)); ok {
		return returnFunc(ctx, bucket)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *s3types.BucketPolicy); ok {
		r0 = returnFunc(ctx, bucket)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3types.BucketPolicy)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, bucket)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockBucketStore_GetBucketPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBucketPolicy'
type MockBucketStore_GetBucketPolicy_Call struct {
	*mock.Call
}

// GetBucketPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
func (_e *MockBucketStore_Expecter) GetBucketPolicy(ctx interface{}, bucket interface{}) *MockBucketStore_GetBucketPolicy_Call {
	return &MockBucketStore_GetBucketPolicy_Call{Call: _e.mock.On("GetBucketPolicy", ctx, bucket)}
}

func (_c *MockBucketStore_GetBucketPolicy_Call) Run(run func(ctx context.Context, bucket string)) *MockBucketStore_GetBucketPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBucketStore_GetBucketPolicy_Call) Return(bucketPolicy *s3types.BucketPolicy, b bool) *MockBucketStore_GetBucketPolicy_Call {
	_c.Call.Return(bucketPolicy, b)
	return _c
}

func (_c *MockBucketStore_GetBucketPolicy_Call) RunAndReturn(run func(ctx context.Context, bucket string) (*s3types.BucketPolicy, bool)) *MockBucketStore_GetBucketPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// SetBucket provides a mock function for the type MockBucketStore
func (_mock *MockBucketStore) SetBucket(name string, bucket s3types.Bucket) {
	_mock.Called(name, bucket)
	return
}

// MockBucketStore_SetBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBucket'
type MockBucketStore_SetBucket_Call struct {
	*mock.Call
}

// SetBucket is a helper method to define mock.On call
//   - name string
//   - bucket s3types.Bucket
func (_e *MockBucketStore_Expecter) SetBucket(name interface{}, bucket interface{}) *MockBucketStore_SetBucket_Call {
	return &MockBucketStore_SetBucket_Call{Call: _e.mock.On("SetBucket", name, bucket)}
}

func (_c *MockBucketStore_SetBucket_Call) Run(run func(name string, bucket s3types.Bucket)) *MockBucketStore_SetBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 s3types.Bucket
		if args[1] != nil {
			arg1 = args[1].(s3types.Bucket)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBucketStore_SetBucket_Call) Return() *MockBucketStore_SetBucket_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBucketStore_SetBucket_Call) RunAndReturn(run func(name string, bucket s3types.Bucket)) *MockBucketStore_SetBucket_Call {
	_c.Run(run)
	return _c
}

// UpdateBucketPolicy provides a mock function for the type MockBucketStore
func (_mock *MockBucketStore) UpdateBucketPolicy(ctx context.Context, bucket string, policy *s3types.BucketPolicy) error {
	ret := _mock.Called(ctx, bucket, policy)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBucketPolicy")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *s3types.BucketPolicy) error); ok {
		r0 = returnFunc(ctx, bucket, policy)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBucketStore_UpdateBucketPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBucketPolicy'
type MockBucketStore_UpdateBucketPolicy_Call struct {
	*mock.Call
}

// UpdateBucketPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - bucket string
//   - policy *s3types.BucketPolicy
func (_e *MockBucketStore_Expecter) UpdateBucketPolicy(ctx interface{}, bucket interface{}, policy interface{}) *MockBucketStore_UpdateBucketPolicy_Call {
	return &MockBucketStore_UpdateBucketPolicy_Call{Call: _e.mock.On("UpdateBucketPolicy", ctx, bucket, policy)}
}

func (_c *MockBucketStore_UpdateBucketPolicy_Call) Run(run func(ctx context.Context, bucket string, policy *s3types.BucketPolicy)) *MockBucketStore_UpdateBucketPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *s3types.BucketPolicy
		if args[2] != nil {
			arg2 = args[2].(*s3types.BucketPolicy)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockBucketStore_UpdateBucketPolicy_Call) Return(err error) *MockBucketStore_UpdateBucketPolicy_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBucketStore_UpdateBucketPolicy_Call) RunAndReturn(run func(ctx context.Context, bucket string, policy *s3types.BucketPolicy) error) *MockBucketStore_UpdateBucketPolicy_Call {
	_c.Call.Return(run)
	return _c
}
