// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/LeeDigitalWorks/zapfs/pkg/taskqueue"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// Handle provides a mock function for the type MockHandler
func (_mock *MockHandler) Handle(ctx context.Context, task *taskqueue.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Handle")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *taskqueue.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Handle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handle'
type MockHandler_Handle_Call struct {
	*mock.Call
}

// Handle is a helper method to define mock.On call
//   - ctx context.Context
//   - task *taskqueue.Task
func (_e *MockHandler_Expecter) Handle(ctx interface{}, task interface{}) *MockHandler_Handle_Call {
	return &MockHandler_Handle_Call{Call: _e.mock.On("Handle", ctx, task)}
}

func (_c *MockHandler_Handle_Call) Run(run func(ctx context.Context, task *taskqueue.Task)) *MockHandler_Handle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *taskqueue.Task
		if args[1] != nil {
			arg1 = args[1].(*taskqueue.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_Handle_Call) Return(err error) *MockHandler_Handle_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Handle_Call) RunAndReturn(run func(ctx context.Context, task *taskqueue.Task) error) *MockHandler_Handle_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockHandler
func (_mock *MockHandler) Type() taskqueue.TaskType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 taskqueue.TaskType
	if returnFunc, ok := ret.Get(0).(func() taskqueue.TaskType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(taskqueue.TaskType)
	}
	return r0
}

// MockHandler_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockHandler_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockHandler_Expecter) Type() *MockHandler_Type_Call {
	return &MockHandler_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockHandler_Type_Call) Run(run func()) *MockHandler_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHandler_Type_Call) Return(taskType taskqueue.TaskType) *MockHandler_Type_Call {
	_c.Call.Return(taskType)
	return _c
}

func (_c *MockHandler_Type_Call) RunAndReturn(run func() taskqueue.TaskType) *MockHandler_Type_Call {
	_c.Call.Return(run)
	return _c
}
