// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"
	"github.com/LeeDigitalWorks/zapfs/pkg/taskqueue"

	mock "github.com/stretchr/testify/mock"
)

// NewMockQueue creates a new instance of MockQueue. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueue(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueue {
	mock := &MockQueue{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockQueue is an autogenerated mock type for the Queue type
type MockQueue struct {
	mock.Mock
}

type MockQueue_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueue) EXPECT() *MockQueue_Expecter {
	return &MockQueue_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockQueue
func (_mock *MockQueue) Cancel(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockQueue_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockQueue_Expecter) Cancel(ctx interface{}, taskID interface{}) *MockQueue_Cancel_Call {
	return &MockQueue_Cancel_Call{Call: _e.mock.On("Cancel", ctx, taskID)}
}

func (_c *MockQueue_Cancel_Call) Run(run func(ctx context.Context, taskID string)) *MockQueue_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Cancel_Call) Return(err error) *MockQueue_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Cancel_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockQueue_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Cleanup provides a mock function for the type MockQueue
func (_mock *MockQueue) Cleanup(ctx context.Context, olderThan time.Duration) (int, error) {
	ret := _mock.Called(ctx, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for Cleanup")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) (int, error)); ok {
		return returnFunc(ctx, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Duration) int); ok {
		r0 = returnFunc(ctx, olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Duration) error); ok {
		r1 = returnFunc(ctx, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Cleanup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cleanup'
type MockQueue_Cleanup_Call struct {
	*mock.Call
}

// Cleanup is a helper method to define mock.On call
//   - ctx context.Context
//   - olderThan time.Duration
func (_e *MockQueue_Expecter) Cleanup(ctx interface{}, olderThan interface{}) *MockQueue_Cleanup_Call {
	return &MockQueue_Cleanup_Call{Call: _e.mock.On("Cleanup", ctx, olderThan)}
}

func (_c *MockQueue_Cleanup_Call) Run(run func(ctx context.Context, olderThan time.Duration)) *MockQueue_Cleanup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Duration
		if args[1] != nil {
			arg1 = args[1].(time.Duration)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Cleanup_Call) Return(n int, err error) *MockQueue_Cleanup_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockQueue_Cleanup_Call) RunAndReturn(run func(ctx context.Context, olderThan time.Duration) (int, error)) *MockQueue_Cleanup_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockQueue
func (_mock *MockQueue) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockQueue_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockQueue_Expecter) Close() *MockQueue_Close_Call {
	return &MockQueue_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockQueue_Close_Call) Run(run func()) *MockQueue_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockQueue_Close_Call) Return(err error) *MockQueue_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Close_Call) RunAndReturn(run func() error) *MockQueue_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Complete provides a mock function for the type MockQueue
func (_mock *MockQueue) Complete(ctx context.Context, taskID string) error {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Complete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Complete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Complete'
type MockQueue_Complete_Call struct {
	*mock.Call
}

// Complete is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockQueue_Expecter) Complete(ctx interface{}, taskID interface{}) *MockQueue_Complete_Call {
	return &MockQueue_Complete_Call{Call: _e.mock.On("Complete", ctx, taskID)}
}

func (_c *MockQueue_Complete_Call) Run(run func(ctx context.Context, taskID string)) *MockQueue_Complete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Complete_Call) Return(err error) *MockQueue_Complete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Complete_Call) RunAndReturn(run func(ctx context.Context, taskID string) error) *MockQueue_Complete_Call {
	_c.Call.Return(run)
	return _c
}

// Dequeue provides a mock function for the type MockQueue
func (_mock *MockQueue) Dequeue(ctx context.Context, workerID string, taskTypes ...taskqueue.TaskType) (*taskqueue.Task, error) {
	// taskqueue.TaskType
	_va := make([]interface{}, len(taskTypes))
	for _i := range taskTypes {
		_va[_i] = taskTypes[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, workerID)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Dequeue")
	}

	var r0 *taskqueue.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...taskqueue.TaskType) (*taskqueue.Task, error)); ok {
		return returnFunc(ctx, workerID, taskTypes...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...taskqueue.TaskType) *taskqueue.Task); ok {
		r0 = returnFunc(ctx, workerID, taskTypes...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskqueue.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...taskqueue.TaskType) error); ok {
		r1 = returnFunc(ctx, workerID, taskTypes...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Dequeue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Dequeue'
type MockQueue_Dequeue_Call struct {
	*mock.Call
}

// Dequeue is a helper method to define mock.On call
//   - ctx context.Context
//   - workerID string
//   - taskTypes ...taskqueue.TaskType
func (_e *MockQueue_Expecter) Dequeue(ctx interface{}, workerID interface{}, taskTypes ...interface{}) *MockQueue_Dequeue_Call {
	return &MockQueue_Dequeue_Call{Call: _e.mock.On("Dequeue",
		append([]interface{}{ctx, workerID}, taskTypes...)...)}
}

func (_c *MockQueue_Dequeue_Call) Run(run func(ctx context.Context, workerID string, taskTypes ...taskqueue.TaskType)) *MockQueue_Dequeue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []taskqueue.TaskType
		variadicArgs := make([]taskqueue.TaskType, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(taskqueue.TaskType)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockQueue_Dequeue_Call) Return(task *taskqueue.Task, err error) *MockQueue_Dequeue_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockQueue_Dequeue_Call) RunAndReturn(run func(ctx context.Context, workerID string, taskTypes ...taskqueue.TaskType) (*taskqueue.Task, error)) *MockQueue_Dequeue_Call {
	_c.Call.Return(run)
	return _c
}

// Enqueue provides a mock function for the type MockQueue
func (_mock *MockQueue) Enqueue(ctx context.Context, task *taskqueue.Task) error {
	ret := _mock.Called(ctx, task)

	if len(ret) == 0 {
		panic("no return value specified for Enqueue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *taskqueue.Task) error); ok {
		r0 = returnFunc(ctx, task)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Enqueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enqueue'
type MockQueue_Enqueue_Call struct {
	*mock.Call
}

// Enqueue is a helper method to define mock.On call
//   - ctx context.Context
//   - task *taskqueue.Task
func (_e *MockQueue_Expecter) Enqueue(ctx interface{}, task interface{}) *MockQueue_Enqueue_Call {
	return &MockQueue_Enqueue_Call{Call: _e.mock.On("Enqueue", ctx, task)}
}

func (_c *MockQueue_Enqueue_Call) Run(run func(ctx context.Context, task *taskqueue.Task)) *MockQueue_Enqueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *taskqueue.Task
		if args[1] != nil {
			arg1 = args[1].(*taskqueue.Task)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Enqueue_Call) Return(err error) *MockQueue_Enqueue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Enqueue_Call) RunAndReturn(run func(ctx context.Context, task *taskqueue.Task) error) *MockQueue_Enqueue_Call {
	_c.Call.Return(run)
	return _c
}

// Fail provides a mock function for the type MockQueue
func (_mock *MockQueue) Fail(ctx context.Context, taskID string, err error) error {
	ret := _mock.Called(ctx, taskID, err)

	if len(ret) == 0 {
		panic("no return value specified for Fail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, error) error); ok {
		r0 = returnFunc(ctx, taskID, err)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Fail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fail'
type MockQueue_Fail_Call struct {
	*mock.Call
}

// Fail is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - err error
func (_e *MockQueue_Expecter) Fail(ctx interface{}, taskID interface{}, err interface{}) *MockQueue_Fail_Call {
	return &MockQueue_Fail_Call{Call: _e.mock.On("Fail", ctx, taskID, err)}
}

func (_c *MockQueue_Fail_Call) Run(run func(ctx context.Context, taskID string, err error)) *MockQueue_Fail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Fail_Call) Return(err1 error) *MockQueue_Fail_Call {
	_c.Call.Return(err1)
	return _c
}

func (_c *MockQueue_Fail_Call) RunAndReturn(run func(ctx context.Context, taskID string, err error) error) *MockQueue_Fail_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockQueue
func (_mock *MockQueue) Get(ctx context.Context, taskID string) (*taskqueue.Task, error) {
	ret := _mock.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *taskqueue.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*taskqueue.Task, error)); ok {
		return returnFunc(ctx, taskID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *taskqueue.Task); ok {
		r0 = returnFunc(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskqueue.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockQueue_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
func (_e *MockQueue_Expecter) Get(ctx interface{}, taskID interface{}) *MockQueue_Get_Call {
	return &MockQueue_Get_Call{Call: _e.mock.On("Get", ctx, taskID)}
}

func (_c *MockQueue_Get_Call) Run(run func(ctx context.Context, taskID string)) *MockQueue_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_Get_Call) Return(task *taskqueue.Task, err error) *MockQueue_Get_Call {
	_c.Call.Return(task, err)
	return _c
}

func (_c *MockQueue_Get_Call) RunAndReturn(run func(ctx context.Context, taskID string) (*taskqueue.Task, error)) *MockQueue_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Heartbeat provides a mock function for the type MockQueue
func (_mock *MockQueue) Heartbeat(ctx context.Context, taskID string, workerID string) error {
	ret := _mock.Called(ctx, taskID, workerID)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, taskID, workerID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockQueue_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type MockQueue_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - taskID string
//   - workerID string
func (_e *MockQueue_Expecter) Heartbeat(ctx interface{}, taskID interface{}, workerID interface{}) *MockQueue_Heartbeat_Call {
	return &MockQueue_Heartbeat_Call{Call: _e.mock.On("Heartbeat", ctx, taskID, workerID)}
}

func (_c *MockQueue_Heartbeat_Call) Run(run func(ctx context.Context, taskID string, workerID string)) *MockQueue_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockQueue_Heartbeat_Call) Return(err error) *MockQueue_Heartbeat_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockQueue_Heartbeat_Call) RunAndReturn(run func(ctx context.Context, taskID string, workerID string) error) *MockQueue_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockQueue
func (_mock *MockQueue) List(ctx context.Context, filter taskqueue.TaskFilter) ([]*taskqueue.Task, error) {
	ret := _mock.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []*taskqueue.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, taskqueue.TaskFilter) ([]*taskqueue.Task, error)); ok {
		return returnFunc(ctx, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, taskqueue.TaskFilter) []*taskqueue.Task); ok {
		r0 = returnFunc(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*taskqueue.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, taskqueue.TaskFilter) error); ok {
		r1 = returnFunc(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockQueue_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - filter taskqueue.TaskFilter
func (_e *MockQueue_Expecter) List(ctx interface{}, filter interface{}) *MockQueue_List_Call {
	return &MockQueue_List_Call{Call: _e.mock.On("List", ctx, filter)}
}

func (_c *MockQueue_List_Call) Run(run func(ctx context.Context, filter taskqueue.TaskFilter)) *MockQueue_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 taskqueue.TaskFilter
		if args[1] != nil {
			arg1 = args[1].(taskqueue.TaskFilter)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockQueue_List_Call) Return(tasks []*taskqueue.Task, err error) *MockQueue_List_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *MockQueue_List_Call) RunAndReturn(run func(ctx context.Context, filter taskqueue.TaskFilter) ([]*taskqueue.Task, error)) *MockQueue_List_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type MockQueue
func (_mock *MockQueue) Stats(ctx context.Context) (*taskqueue.QueueStats, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 *taskqueue.QueueStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*taskqueue.QueueStats, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *taskqueue.QueueStats); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*taskqueue.QueueStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockQueue_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type MockQueue_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQueue_Expecter) Stats(ctx interface{}) *MockQueue_Stats_Call {
	return &MockQueue_Stats_Call{Call: _e.mock.On("Stats", ctx)}
}

func (_c *MockQueue_Stats_Call) Run(run func(ctx context.Context)) *MockQueue_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockQueue_Stats_Call) Return(queueStats *taskqueue.QueueStats, err error) *MockQueue_Stats_Call {
	_c.Call.Return(queueStats, err)
	return _c
}

func (_c *MockQueue_Stats_Call) RunAndReturn(run func(ctx context.Context) (*taskqueue.QueueStats, error)) *MockQueue_Stats_Call {
	_c.Call.Return(run)
	return _c
}
