// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/LeeDigitalWorks/zapfs/pkg/metadata/data"
	"github.com/LeeDigitalWorks/zapfs/pkg/metadata/filter"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilter creates a new instance of MockFilter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilter {
	mock := &MockFilter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilter is an autogenerated mock type for the Filter type
type MockFilter struct {
	mock.Mock
}

type MockFilter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilter) EXPECT() *MockFilter_Expecter {
	return &MockFilter_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockFilter
func (_mock *MockFilter) Run(d *data.Data) (filter.Response, error) {
	ret := _mock.Called(d)

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 filter.Response
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*data.Data) (filter.Response, error)); ok {
		return returnFunc(d)
	}
	if returnFunc, ok := ret.Get(0).(func(*data.Data) filter.Response); ok {
		r0 = returnFunc(d)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(filter.Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*data.Data) error); ok {
		r1 = returnFunc(d)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilter_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockFilter_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - d *data.Data
func (_e *MockFilter_Expecter) Run(d interface{}) *MockFilter_Run_Call {
	return &MockFilter_Run_Call{Call: _e.mock.On("Run", d)}
}

func (_c *MockFilter_Run_Call) Run(run func(d *data.Data)) *MockFilter_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *data.Data
		if args[0] != nil {
			arg0 = args[0].(*data.Data)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilter_Run_Call) Return(response filter.Response, err error) *MockFilter_Run_Call {
	_c.Call.Return(response, err)
	return _c
}

func (_c *MockFilter_Run_Call) RunAndReturn(run func(d *data.Data) (filter.Response, error)) *MockFilter_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Type provides a mock function for the type MockFilter
func (_mock *MockFilter) Type() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Type")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockFilter_Type_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Type'
type MockFilter_Type_Call struct {
	*mock.Call
}

// Type is a helper method to define mock.On call
func (_e *MockFilter_Expecter) Type() *MockFilter_Type_Call {
	return &MockFilter_Type_Call{Call: _e.mock.On("Type")}
}

func (_c *MockFilter_Type_Call) Run(run func()) *MockFilter_Type_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilter_Type_Call) Return(s string) *MockFilter_Type_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockFilter_Type_Call) RunAndReturn(run func() string) *MockFilter_Type_Call {
	_c.Call.Return(run)
	return _c
}
