// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/LeeDigitalWorks/zapfs/pkg/metadata/client"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFile creates a new instance of MockFile. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFile(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFile {
	mock := &MockFile{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFile is an autogenerated mock type for the File type
type MockFile struct {
	mock.Mock
}

type MockFile_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFile) EXPECT() *MockFile_Expecter {
	return &MockFile_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockFile
func (_mock *MockFile) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockFile_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockFile_Expecter) Close() *MockFile_Close_Call {
	return &MockFile_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockFile_Close_Call) Run(run func()) *MockFile_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFile_Close_Call) Return(err error) *MockFile_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_Close_Call) RunAndReturn(run func() error) *MockFile_Close_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRefCount provides a mock function for the type MockFile
func (_mock *MockFile) DecrementRefCount(ctx context.Context, address string, chunkID string, expectedRefCount uint32) (*client.DecrementRefCountResult, error) {
	ret := _mock.Called(ctx, address, chunkID, expectedRefCount)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRefCount")
	}

	var r0 *client.DecrementRefCountResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint32) (*client.DecrementRefCountResult, error)); ok {
		return returnFunc(ctx, address, chunkID, expectedRefCount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint32) *client.DecrementRefCountResult); ok {
		r0 = returnFunc(ctx, address, chunkID, expectedRefCount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.DecrementRefCountResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uint32) error); ok {
		r1 = returnFunc(ctx, address, chunkID, expectedRefCount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_DecrementRefCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRefCount'
type MockFile_DecrementRefCount_Call struct {
	*mock.Call
}

// DecrementRefCount is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - chunkID string
//   - expectedRefCount uint32
func (_e *MockFile_Expecter) DecrementRefCount(ctx interface{}, address interface{}, chunkID interface{}, expectedRefCount interface{}) *MockFile_DecrementRefCount_Call {
	return &MockFile_DecrementRefCount_Call{Call: _e.mock.On("DecrementRefCount", ctx, address, chunkID, expectedRefCount)}
}

func (_c *MockFile_DecrementRefCount_Call) Run(run func(ctx context.Context, address string, chunkID string, expectedRefCount uint32)) *MockFile_DecrementRefCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint32
		if args[3] != nil {
			arg3 = args[3].(uint32)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFile_DecrementRefCount_Call) Return(decrementRefCountResult *client.DecrementRefCountResult, err error) *MockFile_DecrementRefCount_Call {
	_c.Call.Return(decrementRefCountResult, err)
	return _c
}

func (_c *MockFile_DecrementRefCount_Call) RunAndReturn(run func(ctx context.Context, address string, chunkID string, expectedRefCount uint32) (*client.DecrementRefCountResult, error)) *MockFile_DecrementRefCount_Call {
	_c.Call.Return(run)
	return _c
}

// DecrementRefCountBatch provides a mock function for the type MockFile
func (_mock *MockFile) DecrementRefCountBatch(ctx context.Context, address string, chunks []client.DecrementRefCountRequest) ([]*client.DecrementRefCountResult, error) {
	ret := _mock.Called(ctx, address, chunks)

	if len(ret) == 0 {
		panic("no return value specified for DecrementRefCountBatch")
	}

	var r0 []*client.DecrementRefCountResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []client.DecrementRefCountRequest) ([]*client.DecrementRefCountResult, error)); ok {
		return returnFunc(ctx, address, chunks)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []client.DecrementRefCountRequest) []*client.DecrementRefCountResult); ok {
		r0 = returnFunc(ctx, address, chunks)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*client.DecrementRefCountResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []client.DecrementRefCountRequest) error); ok {
		r1 = returnFunc(ctx, address, chunks)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_DecrementRefCountBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecrementRefCountBatch'
type MockFile_DecrementRefCountBatch_Call struct {
	*mock.Call
}

// DecrementRefCountBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - chunks []client.DecrementRefCountRequest
func (_e *MockFile_Expecter) DecrementRefCountBatch(ctx interface{}, address interface{}, chunks interface{}) *MockFile_DecrementRefCountBatch_Call {
	return &MockFile_DecrementRefCountBatch_Call{Call: _e.mock.On("DecrementRefCountBatch", ctx, address, chunks)}
}

func (_c *MockFile_DecrementRefCountBatch_Call) Run(run func(ctx context.Context, address string, chunks []client.DecrementRefCountRequest)) *MockFile_DecrementRefCountBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []client.DecrementRefCountRequest
		if args[2] != nil {
			arg2 = args[2].([]client.DecrementRefCountRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFile_DecrementRefCountBatch_Call) Return(decrementRefCountResults []*client.DecrementRefCountResult, err error) *MockFile_DecrementRefCountBatch_Call {
	_c.Call.Return(decrementRefCountResults, err)
	return _c
}

func (_c *MockFile_DecrementRefCountBatch_Call) RunAndReturn(run func(ctx context.Context, address string, chunks []client.DecrementRefCountRequest) ([]*client.DecrementRefCountResult, error)) *MockFile_DecrementRefCountBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetChunk provides a mock function for the type MockFile
func (_mock *MockFile) GetChunk(ctx context.Context, address string, chunkID string, writer client.ObjectWriter) error {
	ret := _mock.Called(ctx, address, chunkID, writer)

	if len(ret) == 0 {
		panic("no return value specified for GetChunk")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ObjectWriter) error); ok {
		r0 = returnFunc(ctx, address, chunkID, writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_GetChunk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChunk'
type MockFile_GetChunk_Call struct {
	*mock.Call
}

// GetChunk is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - chunkID string
//   - writer client.ObjectWriter
func (_e *MockFile_Expecter) GetChunk(ctx interface{}, address interface{}, chunkID interface{}, writer interface{}) *MockFile_GetChunk_Call {
	return &MockFile_GetChunk_Call{Call: _e.mock.On("GetChunk", ctx, address, chunkID, writer)}
}

func (_c *MockFile_GetChunk_Call) Run(run func(ctx context.Context, address string, chunkID string, writer client.ObjectWriter)) *MockFile_GetChunk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ObjectWriter
		if args[3] != nil {
			arg3 = args[3].(client.ObjectWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFile_GetChunk_Call) Return(err error) *MockFile_GetChunk_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_GetChunk_Call) RunAndReturn(run func(ctx context.Context, address string, chunkID string, writer client.ObjectWriter) error) *MockFile_GetChunk_Call {
	_c.Call.Return(run)
	return _c
}

// GetChunkRange provides a mock function for the type MockFile
func (_mock *MockFile) GetChunkRange(ctx context.Context, address string, chunkID string, offset uint64, length uint64, writer client.ObjectWriter) error {
	ret := _mock.Called(ctx, address, chunkID, offset, length, writer)

	if len(ret) == 0 {
		panic("no return value specified for GetChunkRange")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64, uint64, client.ObjectWriter) error); ok {
		r0 = returnFunc(ctx, address, chunkID, offset, length, writer)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFile_GetChunkRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChunkRange'
type MockFile_GetChunkRange_Call struct {
	*mock.Call
}

// GetChunkRange is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - chunkID string
//   - offset uint64
//   - length uint64
//   - writer client.ObjectWriter
func (_e *MockFile_Expecter) GetChunkRange(ctx interface{}, address interface{}, chunkID interface{}, offset interface{}, length interface{}, writer interface{}) *MockFile_GetChunkRange_Call {
	return &MockFile_GetChunkRange_Call{Call: _e.mock.On("GetChunkRange", ctx, address, chunkID, offset, length, writer)}
}

func (_c *MockFile_GetChunkRange_Call) Run(run func(ctx context.Context, address string, chunkID string, offset uint64, length uint64, writer client.ObjectWriter)) *MockFile_GetChunkRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		var arg5 client.ObjectWriter
		if args[5] != nil {
			arg5 = args[5].(client.ObjectWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockFile_GetChunkRange_Call) Return(err error) *MockFile_GetChunkRange_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFile_GetChunkRange_Call) RunAndReturn(run func(ctx context.Context, address string, chunkID string, offset uint64, length uint64, writer client.ObjectWriter) error) *MockFile_GetChunkRange_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockFile
func (_mock *MockFile) GetObject(ctx context.Context, address string, objectID string, writer client.ObjectWriter) (string, error) {
	ret := _mock.Called(ctx, address, objectID, writer)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ObjectWriter) (string, error)); ok {
		return returnFunc(ctx, address, objectID, writer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, client.ObjectWriter) string); ok {
		r0 = returnFunc(ctx, address, objectID, writer)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, client.ObjectWriter) error); ok {
		r1 = returnFunc(ctx, address, objectID, writer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockFile_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - objectID string
//   - writer client.ObjectWriter
func (_e *MockFile_Expecter) GetObject(ctx interface{}, address interface{}, objectID interface{}, writer interface{}) *MockFile_GetObject_Call {
	return &MockFile_GetObject_Call{Call: _e.mock.On("GetObject", ctx, address, objectID, writer)}
}

func (_c *MockFile_GetObject_Call) Run(run func(ctx context.Context, address string, objectID string, writer client.ObjectWriter)) *MockFile_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 client.ObjectWriter
		if args[3] != nil {
			arg3 = args[3].(client.ObjectWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockFile_GetObject_Call) Return(etag string, err error) *MockFile_GetObject_Call {
	_c.Call.Return(etag, err)
	return _c
}

func (_c *MockFile_GetObject_Call) RunAndReturn(run func(ctx context.Context, address string, objectID string, writer client.ObjectWriter) (string, error)) *MockFile_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObjectRange provides a mock function for the type MockFile
func (_mock *MockFile) GetObjectRange(ctx context.Context, address string, objectID string, offset uint64, length uint64, writer client.ObjectWriter) (string, error) {
	ret := _mock.Called(ctx, address, objectID, offset, length, writer)

	if len(ret) == 0 {
		panic("no return value specified for GetObjectRange")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64, uint64, client.ObjectWriter) (string, error)); ok {
		return returnFunc(ctx, address, objectID, offset, length, writer)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, uint64, uint64, client.ObjectWriter) string); ok {
		r0 = returnFunc(ctx, address, objectID, offset, length, writer)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, uint64, uint64, client.ObjectWriter) error); ok {
		r1 = returnFunc(ctx, address, objectID, offset, length, writer)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_GetObjectRange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObjectRange'
type MockFile_GetObjectRange_Call struct {
	*mock.Call
}

// GetObjectRange is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - objectID string
//   - offset uint64
//   - length uint64
//   - writer client.ObjectWriter
func (_e *MockFile_Expecter) GetObjectRange(ctx interface{}, address interface{}, objectID interface{}, offset interface{}, length interface{}, writer interface{}) *MockFile_GetObjectRange_Call {
	return &MockFile_GetObjectRange_Call{Call: _e.mock.On("GetObjectRange", ctx, address, objectID, offset, length, writer)}
}

func (_c *MockFile_GetObjectRange_Call) Run(run func(ctx context.Context, address string, objectID string, offset uint64, length uint64, writer client.ObjectWriter)) *MockFile_GetObjectRange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 uint64
		if args[3] != nil {
			arg3 = args[3].(uint64)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		var arg5 client.ObjectWriter
		if args[5] != nil {
			arg5 = args[5].(client.ObjectWriter)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockFile_GetObjectRange_Call) Return(etag string, err error) *MockFile_GetObjectRange_Call {
	_c.Call.Return(etag, err)
	return _c
}

func (_c *MockFile_GetObjectRange_Call) RunAndReturn(run func(ctx context.Context, address string, objectID string, offset uint64, length uint64, writer client.ObjectWriter) (string, error)) *MockFile_GetObjectRange_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type MockFile
func (_mock *MockFile) PutObject(ctx context.Context, address string, objectID string, data io.Reader, totalSize uint64) (*client.PutObjectResult, error) {
	ret := _mock.Called(ctx, address, objectID, data, totalSize)

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *client.PutObjectResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, uint64) (*client.PutObjectResult, error)); ok {
		return returnFunc(ctx, address, objectID, data, totalSize)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, io.Reader, uint64) *client.PutObjectResult); ok {
		r0 = returnFunc(ctx, address, objectID, data, totalSize)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.PutObjectResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, io.Reader, uint64) error); ok {
		r1 = returnFunc(ctx, address, objectID, data, totalSize)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFile_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type MockFile_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - address string
//   - objectID string
//   - data io.Reader
//   - totalSize uint64
func (_e *MockFile_Expecter) PutObject(ctx interface{}, address interface{}, objectID interface{}, data interface{}, totalSize interface{}) *MockFile_PutObject_Call {
	return &MockFile_PutObject_Call{Call: _e.mock.On("PutObject", ctx, address, objectID, data, totalSize)}
}

func (_c *MockFile_PutObject_Call) Run(run func(ctx context.Context, address string, objectID string, data io.Reader, totalSize uint64)) *MockFile_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 io.Reader
		if args[3] != nil {
			arg3 = args[3].(io.Reader)
		}
		var arg4 uint64
		if args[4] != nil {
			arg4 = args[4].(uint64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockFile_PutObject_Call) Return(putObjectResult *client.PutObjectResult, err error) *MockFile_PutObject_Call {
	_c.Call.Return(putObjectResult, err)
	return _c
}

func (_c *MockFile_PutObject_Call) RunAndReturn(run func(ctx context.Context, address string, objectID string, data io.Reader, totalSize uint64) (*client.PutObjectResult, error)) *MockFile_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
