// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.33.2
// source: iam.proto

package iam_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	IAMService_GetCredential_FullMethodName     = "/iam_pb.IAMService/GetCredential"
	IAMService_StreamCredentials_FullMethodName = "/iam_pb.IAMService/StreamCredentials"
	IAMService_ListCredentials_FullMethodName   = "/iam_pb.IAMService/ListCredentials"
	IAMService_GetIAMVersion_FullMethodName     = "/iam_pb.IAMService/GetIAMVersion"
)

// IAMServiceClient is the client API for IAMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IAMServiceClient interface {
	// GetCredential retrieves a credential by access key
	// Returns decrypted secret for trusted metadata services to verify signatures locally
	GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error)
	// StreamCredentials streams credential changes in real-time
	// Metadata services use this to keep their caches in sync
	StreamCredentials(ctx context.Context, in *StreamCredentialsRequest, opts ...grpc.CallOption) (IAMService_StreamCredentialsClient, error)
	// ListCredentials returns all credentials (for initial sync on startup)
	ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (IAMService_ListCredentialsClient, error)
	// GetIAMVersion returns the current IAM data version
	GetIAMVersion(ctx context.Context, in *GetIAMVersionRequest, opts ...grpc.CallOption) (*GetIAMVersionResponse, error)
}

type iAMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIAMServiceClient(cc grpc.ClientConnInterface) IAMServiceClient {
	return &iAMServiceClient{cc}
}

func (c *iAMServiceClient) GetCredential(ctx context.Context, in *GetCredentialRequest, opts ...grpc.CallOption) (*GetCredentialResponse, error) {
	out := new(GetCredentialResponse)
	err := c.cc.Invoke(ctx, IAMService_GetCredential_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iAMServiceClient) StreamCredentials(ctx context.Context, in *StreamCredentialsRequest, opts ...grpc.CallOption) (IAMService_StreamCredentialsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IAMService_ServiceDesc.Streams[0], IAMService_StreamCredentials_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &iAMServiceStreamCredentialsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IAMService_StreamCredentialsClient interface {
	Recv() (*CredentialEvent, error)
	grpc.ClientStream
}

type iAMServiceStreamCredentialsClient struct {
	grpc.ClientStream
}

func (x *iAMServiceStreamCredentialsClient) Recv() (*CredentialEvent, error) {
	m := new(CredentialEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iAMServiceClient) ListCredentials(ctx context.Context, in *ListCredentialsRequest, opts ...grpc.CallOption) (IAMService_ListCredentialsClient, error) {
	stream, err := c.cc.NewStream(ctx, &IAMService_ServiceDesc.Streams[1], IAMService_ListCredentials_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &iAMServiceListCredentialsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IAMService_ListCredentialsClient interface {
	Recv() (*Credential, error)
	grpc.ClientStream
}

type iAMServiceListCredentialsClient struct {
	grpc.ClientStream
}

func (x *iAMServiceListCredentialsClient) Recv() (*Credential, error) {
	m := new(Credential)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *iAMServiceClient) GetIAMVersion(ctx context.Context, in *GetIAMVersionRequest, opts ...grpc.CallOption) (*GetIAMVersionResponse, error) {
	out := new(GetIAMVersionResponse)
	err := c.cc.Invoke(ctx, IAMService_GetIAMVersion_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IAMServiceServer is the server API for IAMService service.
// All implementations must embed UnimplementedIAMServiceServer
// for forward compatibility
type IAMServiceServer interface {
	// GetCredential retrieves a credential by access key
	// Returns decrypted secret for trusted metadata services to verify signatures locally
	GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error)
	// StreamCredentials streams credential changes in real-time
	// Metadata services use this to keep their caches in sync
	StreamCredentials(*StreamCredentialsRequest, IAMService_StreamCredentialsServer) error
	// ListCredentials returns all credentials (for initial sync on startup)
	ListCredentials(*ListCredentialsRequest, IAMService_ListCredentialsServer) error
	// GetIAMVersion returns the current IAM data version
	GetIAMVersion(context.Context, *GetIAMVersionRequest) (*GetIAMVersionResponse, error)
	mustEmbedUnimplementedIAMServiceServer()
}

// UnimplementedIAMServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIAMServiceServer struct {
}

func (UnimplementedIAMServiceServer) GetCredential(context.Context, *GetCredentialRequest) (*GetCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCredential not implemented")
}
func (UnimplementedIAMServiceServer) StreamCredentials(*StreamCredentialsRequest, IAMService_StreamCredentialsServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamCredentials not implemented")
}
func (UnimplementedIAMServiceServer) ListCredentials(*ListCredentialsRequest, IAMService_ListCredentialsServer) error {
	return status.Errorf(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedIAMServiceServer) GetIAMVersion(context.Context, *GetIAMVersionRequest) (*GetIAMVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIAMVersion not implemented")
}
func (UnimplementedIAMServiceServer) mustEmbedUnimplementedIAMServiceServer() {}

// UnsafeIAMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IAMServiceServer will
// result in compilation errors.
type UnsafeIAMServiceServer interface {
	mustEmbedUnimplementedIAMServiceServer()
}

func RegisterIAMServiceServer(s grpc.ServiceRegistrar, srv IAMServiceServer) {
	s.RegisterService(&IAMService_ServiceDesc, srv)
}

func _IAMService_GetCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetCredential(ctx, req.(*GetCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IAMService_StreamCredentials_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamCredentialsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IAMServiceServer).StreamCredentials(m, &iAMServiceStreamCredentialsServer{stream})
}

type IAMService_StreamCredentialsServer interface {
	Send(*CredentialEvent) error
	grpc.ServerStream
}

type iAMServiceStreamCredentialsServer struct {
	grpc.ServerStream
}

func (x *iAMServiceStreamCredentialsServer) Send(m *CredentialEvent) error {
	return x.ServerStream.SendMsg(m)
}

func _IAMService_ListCredentials_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListCredentialsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IAMServiceServer).ListCredentials(m, &iAMServiceListCredentialsServer{stream})
}

type IAMService_ListCredentialsServer interface {
	Send(*Credential) error
	grpc.ServerStream
}

type iAMServiceListCredentialsServer struct {
	grpc.ServerStream
}

func (x *iAMServiceListCredentialsServer) Send(m *Credential) error {
	return x.ServerStream.SendMsg(m)
}

func _IAMService_GetIAMVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIAMVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IAMServiceServer).GetIAMVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IAMService_GetIAMVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IAMServiceServer).GetIAMVersion(ctx, req.(*GetIAMVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IAMService_ServiceDesc is the grpc.ServiceDesc for IAMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IAMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam_pb.IAMService",
	HandlerType: (*IAMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCredential",
			Handler:    _IAMService_GetCredential_Handler,
		},
		{
			MethodName: "GetIAMVersion",
			Handler:    _IAMService_GetIAMVersion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamCredentials",
			Handler:       _IAMService_StreamCredentials_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListCredentials",
			Handler:       _IAMService_ListCredentials_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "iam.proto",
}
