// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/LeeDigitalWorks/zapfs/proto/metadata_pb"
	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockMetadataServiceClient creates a new instance of MockMetadataServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataServiceClient {
	mock := &MockMetadataServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataServiceClient is an autogenerated mock type for the MetadataServiceClient type
type MockMetadataServiceClient struct {
	mock.Mock
}

type MockMetadataServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataServiceClient) EXPECT() *MockMetadataServiceClient_Expecter {
	return &MockMetadataServiceClient_Expecter{mock: &_m.Mock}
}

// CreateCollection provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) CreateCollection(ctx context.Context, in *metadata_pb.CreateCollectionRequest, opts ...grpc.CallOption) (*metadata_pb.CreateCollectionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 *metadata_pb.CreateCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.CreateCollectionRequest, ...grpc.CallOption) (*metadata_pb.CreateCollectionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.CreateCollectionRequest, ...grpc.CallOption) *metadata_pb.CreateCollectionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.CreateCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.CreateCollectionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockMetadataServiceClient_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.CreateCollectionRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) CreateCollection(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_CreateCollection_Call {
	return &MockMetadataServiceClient_CreateCollection_Call{Call: _e.mock.On("CreateCollection",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_CreateCollection_Call) Run(run func(ctx context.Context, in *metadata_pb.CreateCollectionRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.CreateCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.CreateCollectionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_CreateCollection_Call) Return(createCollectionResponse *metadata_pb.CreateCollectionResponse, err error) *MockMetadataServiceClient_CreateCollection_Call {
	_c.Call.Return(createCollectionResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_CreateCollection_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.CreateCollectionRequest, opts ...grpc.CallOption) (*metadata_pb.CreateCollectionResponse, error)) *MockMetadataServiceClient_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) DeleteCollection(ctx context.Context, in *metadata_pb.DeleteCollectionRequest, opts ...grpc.CallOption) (*metadata_pb.DeleteCollectionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 *metadata_pb.DeleteCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.DeleteCollectionRequest, ...grpc.CallOption) (*metadata_pb.DeleteCollectionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.DeleteCollectionRequest, ...grpc.CallOption) *metadata_pb.DeleteCollectionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.DeleteCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.DeleteCollectionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockMetadataServiceClient_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.DeleteCollectionRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) DeleteCollection(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_DeleteCollection_Call {
	return &MockMetadataServiceClient_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_DeleteCollection_Call) Run(run func(ctx context.Context, in *metadata_pb.DeleteCollectionRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.DeleteCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.DeleteCollectionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_DeleteCollection_Call) Return(deleteCollectionResponse *metadata_pb.DeleteCollectionResponse, err error) *MockMetadataServiceClient_DeleteCollection_Call {
	_c.Call.Return(deleteCollectionResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_DeleteCollection_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.DeleteCollectionRequest, opts ...grpc.CallOption) (*metadata_pb.DeleteCollectionResponse, error)) *MockMetadataServiceClient_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) DeleteObject(ctx context.Context, in *metadata_pb.DeleteObjectRequest, opts ...grpc.CallOption) (*metadata_pb.DeleteObjectResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *metadata_pb.DeleteObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.DeleteObjectRequest, ...grpc.CallOption) (*metadata_pb.DeleteObjectResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.DeleteObjectRequest, ...grpc.CallOption) *metadata_pb.DeleteObjectResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.DeleteObjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.DeleteObjectRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockMetadataServiceClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.DeleteObjectRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) DeleteObject(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_DeleteObject_Call {
	return &MockMetadataServiceClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_DeleteObject_Call) Run(run func(ctx context.Context, in *metadata_pb.DeleteObjectRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.DeleteObjectRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.DeleteObjectRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_DeleteObject_Call) Return(deleteObjectResponse *metadata_pb.DeleteObjectResponse, err error) *MockMetadataServiceClient_DeleteObject_Call {
	_c.Call.Return(deleteObjectResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.DeleteObjectRequest, opts ...grpc.CallOption) (*metadata_pb.DeleteObjectResponse, error)) *MockMetadataServiceClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) GetObject(ctx context.Context, in *metadata_pb.GetObjectRequest, opts ...grpc.CallOption) (*metadata_pb.GetObjectResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *metadata_pb.GetObjectResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.GetObjectRequest, ...grpc.CallOption) (*metadata_pb.GetObjectResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.GetObjectRequest, ...grpc.CallOption) *metadata_pb.GetObjectResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.GetObjectResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.GetObjectRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type MockMetadataServiceClient_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.GetObjectRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) GetObject(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_GetObject_Call {
	return &MockMetadataServiceClient_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_GetObject_Call) Run(run func(ctx context.Context, in *metadata_pb.GetObjectRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.GetObjectRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.GetObjectRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_GetObject_Call) Return(getObjectResponse *metadata_pb.GetObjectResponse, err error) *MockMetadataServiceClient_GetObject_Call {
	_c.Call.Return(getObjectResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_GetObject_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.GetObjectRequest, opts ...grpc.CallOption) (*metadata_pb.GetObjectResponse, error)) *MockMetadataServiceClient_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) ListCollections(ctx context.Context, in *metadata_pb.ListCollectionsRequest, opts ...grpc.CallOption) (*metadata_pb.ListCollectionsResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 *metadata_pb.ListCollectionsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.ListCollectionsRequest, ...grpc.CallOption) (*metadata_pb.ListCollectionsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.ListCollectionsRequest, ...grpc.CallOption) *metadata_pb.ListCollectionsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.ListCollectionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.ListCollectionsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockMetadataServiceClient_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.ListCollectionsRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) ListCollections(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_ListCollections_Call {
	return &MockMetadataServiceClient_ListCollections_Call{Call: _e.mock.On("ListCollections",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_ListCollections_Call) Run(run func(ctx context.Context, in *metadata_pb.ListCollectionsRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.ListCollectionsRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.ListCollectionsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_ListCollections_Call) Return(listCollectionsResponse *metadata_pb.ListCollectionsResponse, err error) *MockMetadataServiceClient_ListCollections_Call {
	_c.Call.Return(listCollectionsResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_ListCollections_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.ListCollectionsRequest, opts ...grpc.CallOption) (*metadata_pb.ListCollectionsResponse, error)) *MockMetadataServiceClient_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjects provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) ListObjects(ctx context.Context, in *metadata_pb.ListObjectsRequest, opts ...grpc.CallOption) (*metadata_pb.ListObjectsResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListObjects")
	}

	var r0 *metadata_pb.ListObjectsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.ListObjectsRequest, ...grpc.CallOption) (*metadata_pb.ListObjectsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.ListObjectsRequest, ...grpc.CallOption) *metadata_pb.ListObjectsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.ListObjectsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.ListObjectsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_ListObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjects'
type MockMetadataServiceClient_ListObjects_Call struct {
	*mock.Call
}

// ListObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.ListObjectsRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) ListObjects(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_ListObjects_Call {
	return &MockMetadataServiceClient_ListObjects_Call{Call: _e.mock.On("ListObjects",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_ListObjects_Call) Run(run func(ctx context.Context, in *metadata_pb.ListObjectsRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_ListObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.ListObjectsRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.ListObjectsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_ListObjects_Call) Return(listObjectsResponse *metadata_pb.ListObjectsResponse, err error) *MockMetadataServiceClient_ListObjects_Call {
	_c.Call.Return(listObjectsResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_ListObjects_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.ListObjectsRequest, opts ...grpc.CallOption) (*metadata_pb.ListObjectsResponse, error)) *MockMetadataServiceClient_ListObjects_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) Ping(ctx context.Context, in *metadata_pb.PingRequest, opts ...grpc.CallOption) (*metadata_pb.PingResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *metadata_pb.PingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.PingRequest, ...grpc.CallOption) (*metadata_pb.PingResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.PingRequest, ...grpc.CallOption) *metadata_pb.PingResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metadata_pb.PingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.PingRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockMetadataServiceClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.PingRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_Ping_Call {
	return &MockMetadataServiceClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_Ping_Call) Run(run func(ctx context.Context, in *metadata_pb.PingRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.PingRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.PingRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_Ping_Call) Return(pingResponse *metadata_pb.PingResponse, err error) *MockMetadataServiceClient_Ping_Call {
	_c.Call.Return(pingResponse, err)
	return _c
}

func (_c *MockMetadataServiceClient_Ping_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.PingRequest, opts ...grpc.CallOption) (*metadata_pb.PingResponse, error)) *MockMetadataServiceClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// StreamChunksForServer provides a mock function for the type MockMetadataServiceClient
func (_mock *MockMetadataServiceClient) StreamChunksForServer(ctx context.Context, in *metadata_pb.StreamChunksForServerRequest, opts ...grpc.CallOption) (metadata_pb.MetadataService_StreamChunksForServerClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for StreamChunksForServer")
	}

	var r0 metadata_pb.MetadataService_StreamChunksForServerClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.StreamChunksForServerRequest, ...grpc.CallOption) (metadata_pb.MetadataService_StreamChunksForServerClient, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *metadata_pb.StreamChunksForServerRequest, ...grpc.CallOption) metadata_pb.MetadataService_StreamChunksForServerClient); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(metadata_pb.MetadataService_StreamChunksForServerClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *metadata_pb.StreamChunksForServerRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataServiceClient_StreamChunksForServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StreamChunksForServer'
type MockMetadataServiceClient_StreamChunksForServer_Call struct {
	*mock.Call
}

// StreamChunksForServer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *metadata_pb.StreamChunksForServerRequest
//   - opts ...grpc.CallOption
func (_e *MockMetadataServiceClient_Expecter) StreamChunksForServer(ctx interface{}, in interface{}, opts ...interface{}) *MockMetadataServiceClient_StreamChunksForServer_Call {
	return &MockMetadataServiceClient_StreamChunksForServer_Call{Call: _e.mock.On("StreamChunksForServer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockMetadataServiceClient_StreamChunksForServer_Call) Run(run func(ctx context.Context, in *metadata_pb.StreamChunksForServerRequest, opts ...grpc.CallOption)) *MockMetadataServiceClient_StreamChunksForServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *metadata_pb.StreamChunksForServerRequest
		if args[1] != nil {
			arg1 = args[1].(*metadata_pb.StreamChunksForServerRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockMetadataServiceClient_StreamChunksForServer_Call) Return(metadataService_StreamChunksForServerClient metadata_pb.MetadataService_StreamChunksForServerClient, err error) *MockMetadataServiceClient_StreamChunksForServer_Call {
	_c.Call.Return(metadataService_StreamChunksForServerClient, err)
	return _c
}

func (_c *MockMetadataServiceClient_StreamChunksForServer_Call) RunAndReturn(run func(ctx context.Context, in *metadata_pb.StreamChunksForServerRequest, opts ...grpc.CallOption) (metadata_pb.MetadataService_StreamChunksForServerClient, error)) *MockMetadataServiceClient_StreamChunksForServer_Call {
	_c.Call.Return(run)
	return _c
}
