// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"github.com/LeeDigitalWorks/zapfs/proto/manager_pb"

	mock "github.com/stretchr/testify/mock"
	"google.golang.org/grpc"
)

// NewMockManagerServiceClient creates a new instance of MockManagerServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockManagerServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockManagerServiceClient {
	mock := &MockManagerServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockManagerServiceClient is an autogenerated mock type for the ManagerServiceClient type
type MockManagerServiceClient struct {
	mock.Mock
}

type MockManagerServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockManagerServiceClient) EXPECT() *MockManagerServiceClient_Expecter {
	return &MockManagerServiceClient_Expecter{mock: &_m.Mock}
}

// CreateCollection provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) CreateCollection(ctx context.Context, in *manager_pb.CreateCollectionRequest, opts ...grpc.CallOption) (*manager_pb.CreateCollectionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateCollection")
	}

	var r0 *manager_pb.CreateCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.CreateCollectionRequest, ...grpc.CallOption) (*manager_pb.CreateCollectionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.CreateCollectionRequest, ...grpc.CallOption) *manager_pb.CreateCollectionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.CreateCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.CreateCollectionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_CreateCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateCollection'
type MockManagerServiceClient_CreateCollection_Call struct {
	*mock.Call
}

// CreateCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.CreateCollectionRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) CreateCollection(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_CreateCollection_Call {
	return &MockManagerServiceClient_CreateCollection_Call{Call: _e.mock.On("CreateCollection",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_CreateCollection_Call) Run(run func(ctx context.Context, in *manager_pb.CreateCollectionRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_CreateCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.CreateCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.CreateCollectionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_CreateCollection_Call) Return(createCollectionResponse *manager_pb.CreateCollectionResponse, err error) *MockManagerServiceClient_CreateCollection_Call {
	_c.Call.Return(createCollectionResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_CreateCollection_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.CreateCollectionRequest, opts ...grpc.CallOption) (*manager_pb.CreateCollectionResponse, error)) *MockManagerServiceClient_CreateCollection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCollection provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) DeleteCollection(ctx context.Context, in *manager_pb.DeleteCollectionRequest, opts ...grpc.CallOption) (*manager_pb.DeleteCollectionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DeleteCollection")
	}

	var r0 *manager_pb.DeleteCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.DeleteCollectionRequest, ...grpc.CallOption) (*manager_pb.DeleteCollectionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.DeleteCollectionRequest, ...grpc.CallOption) *manager_pb.DeleteCollectionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.DeleteCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.DeleteCollectionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_DeleteCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCollection'
type MockManagerServiceClient_DeleteCollection_Call struct {
	*mock.Call
}

// DeleteCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.DeleteCollectionRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) DeleteCollection(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_DeleteCollection_Call {
	return &MockManagerServiceClient_DeleteCollection_Call{Call: _e.mock.On("DeleteCollection",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_DeleteCollection_Call) Run(run func(ctx context.Context, in *manager_pb.DeleteCollectionRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_DeleteCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.DeleteCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.DeleteCollectionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_DeleteCollection_Call) Return(deleteCollectionResponse *manager_pb.DeleteCollectionResponse, err error) *MockManagerServiceClient_DeleteCollection_Call {
	_c.Call.Return(deleteCollectionResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_DeleteCollection_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.DeleteCollectionRequest, opts ...grpc.CallOption) (*manager_pb.DeleteCollectionResponse, error)) *MockManagerServiceClient_DeleteCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetCollection provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) GetCollection(ctx context.Context, in *manager_pb.GetCollectionRequest, opts ...grpc.CallOption) (*manager_pb.GetCollectionResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCollection")
	}

	var r0 *manager_pb.GetCollectionResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetCollectionRequest, ...grpc.CallOption) (*manager_pb.GetCollectionResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetCollectionRequest, ...grpc.CallOption) *manager_pb.GetCollectionResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.GetCollectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.GetCollectionRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_GetCollection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCollection'
type MockManagerServiceClient_GetCollection_Call struct {
	*mock.Call
}

// GetCollection is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.GetCollectionRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) GetCollection(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_GetCollection_Call {
	return &MockManagerServiceClient_GetCollection_Call{Call: _e.mock.On("GetCollection",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_GetCollection_Call) Run(run func(ctx context.Context, in *manager_pb.GetCollectionRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_GetCollection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.GetCollectionRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.GetCollectionRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_GetCollection_Call) Return(getCollectionResponse *manager_pb.GetCollectionResponse, err error) *MockManagerServiceClient_GetCollection_Call {
	_c.Call.Return(getCollectionResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_GetCollection_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.GetCollectionRequest, opts ...grpc.CallOption) (*manager_pb.GetCollectionResponse, error)) *MockManagerServiceClient_GetCollection_Call {
	_c.Call.Return(run)
	return _c
}

// GetReplicationTargets provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) GetReplicationTargets(ctx context.Context, in *manager_pb.GetReplicationTargetsRequest, opts ...grpc.CallOption) (*manager_pb.GetReplicationTargetsResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetReplicationTargets")
	}

	var r0 *manager_pb.GetReplicationTargetsResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetReplicationTargetsRequest, ...grpc.CallOption) (*manager_pb.GetReplicationTargetsResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.GetReplicationTargetsRequest, ...grpc.CallOption) *manager_pb.GetReplicationTargetsResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.GetReplicationTargetsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.GetReplicationTargetsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_GetReplicationTargets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetReplicationTargets'
type MockManagerServiceClient_GetReplicationTargets_Call struct {
	*mock.Call
}

// GetReplicationTargets is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.GetReplicationTargetsRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) GetReplicationTargets(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_GetReplicationTargets_Call {
	return &MockManagerServiceClient_GetReplicationTargets_Call{Call: _e.mock.On("GetReplicationTargets",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_GetReplicationTargets_Call) Run(run func(ctx context.Context, in *manager_pb.GetReplicationTargetsRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_GetReplicationTargets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.GetReplicationTargetsRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.GetReplicationTargetsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_GetReplicationTargets_Call) Return(getReplicationTargetsResponse *manager_pb.GetReplicationTargetsResponse, err error) *MockManagerServiceClient_GetReplicationTargets_Call {
	_c.Call.Return(getReplicationTargetsResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_GetReplicationTargets_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.GetReplicationTargetsRequest, opts ...grpc.CallOption) (*manager_pb.GetReplicationTargetsResponse, error)) *MockManagerServiceClient_GetReplicationTargets_Call {
	_c.Call.Return(run)
	return _c
}

// Heartbeat provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) Heartbeat(ctx context.Context, in *manager_pb.HeartbeatRequest, opts ...grpc.CallOption) (*manager_pb.HeartbeatResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Heartbeat")
	}

	var r0 *manager_pb.HeartbeatResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.HeartbeatRequest, ...grpc.CallOption) (*manager_pb.HeartbeatResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.HeartbeatRequest, ...grpc.CallOption) *manager_pb.HeartbeatResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.HeartbeatResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.HeartbeatRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_Heartbeat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Heartbeat'
type MockManagerServiceClient_Heartbeat_Call struct {
	*mock.Call
}

// Heartbeat is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.HeartbeatRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) Heartbeat(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_Heartbeat_Call {
	return &MockManagerServiceClient_Heartbeat_Call{Call: _e.mock.On("Heartbeat",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_Heartbeat_Call) Run(run func(ctx context.Context, in *manager_pb.HeartbeatRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_Heartbeat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.HeartbeatRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.HeartbeatRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_Heartbeat_Call) Return(heartbeatResponse *manager_pb.HeartbeatResponse, err error) *MockManagerServiceClient_Heartbeat_Call {
	_c.Call.Return(heartbeatResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_Heartbeat_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.HeartbeatRequest, opts ...grpc.CallOption) (*manager_pb.HeartbeatResponse, error)) *MockManagerServiceClient_Heartbeat_Call {
	_c.Call.Return(run)
	return _c
}

// ListCollections provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) ListCollections(ctx context.Context, in *manager_pb.ListCollectionsRequest, opts ...grpc.CallOption) (manager_pb.ManagerService_ListCollectionsClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ListCollections")
	}

	var r0 manager_pb.ManagerService_ListCollectionsClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.ListCollectionsRequest, ...grpc.CallOption) (manager_pb.ManagerService_ListCollectionsClient, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.ListCollectionsRequest, ...grpc.CallOption) manager_pb.ManagerService_ListCollectionsClient); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(manager_pb.ManagerService_ListCollectionsClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.ListCollectionsRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_ListCollections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListCollections'
type MockManagerServiceClient_ListCollections_Call struct {
	*mock.Call
}

// ListCollections is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.ListCollectionsRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) ListCollections(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_ListCollections_Call {
	return &MockManagerServiceClient_ListCollections_Call{Call: _e.mock.On("ListCollections",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_ListCollections_Call) Run(run func(ctx context.Context, in *manager_pb.ListCollectionsRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_ListCollections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.ListCollectionsRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.ListCollectionsRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_ListCollections_Call) Return(managerService_ListCollectionsClient manager_pb.ManagerService_ListCollectionsClient, err error) *MockManagerServiceClient_ListCollections_Call {
	_c.Call.Return(managerService_ListCollectionsClient, err)
	return _c
}

func (_c *MockManagerServiceClient_ListCollections_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.ListCollectionsRequest, opts ...grpc.CallOption) (manager_pb.ManagerService_ListCollectionsClient, error)) *MockManagerServiceClient_ListCollections_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) Ping(ctx context.Context, in *manager_pb.PingRequest, opts ...grpc.CallOption) (*manager_pb.PingResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 *manager_pb.PingResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.PingRequest, ...grpc.CallOption) (*manager_pb.PingResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.PingRequest, ...grpc.CallOption) *manager_pb.PingResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.PingResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.PingRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockManagerServiceClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.PingRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) Ping(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_Ping_Call {
	return &MockManagerServiceClient_Ping_Call{Call: _e.mock.On("Ping",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_Ping_Call) Run(run func(ctx context.Context, in *manager_pb.PingRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.PingRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.PingRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_Ping_Call) Return(pingResponse *manager_pb.PingResponse, err error) *MockManagerServiceClient_Ping_Call {
	_c.Call.Return(pingResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_Ping_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.PingRequest, opts ...grpc.CallOption) (*manager_pb.PingResponse, error)) *MockManagerServiceClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// RaftAddServer provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) RaftAddServer(ctx context.Context, in *manager_pb.RaftAddServerRequest, opts ...grpc.CallOption) (*manager_pb.RaftAddServerResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RaftAddServer")
	}

	var r0 *manager_pb.RaftAddServerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftAddServerRequest, ...grpc.CallOption) (*manager_pb.RaftAddServerResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftAddServerRequest, ...grpc.CallOption) *manager_pb.RaftAddServerResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.RaftAddServerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.RaftAddServerRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_RaftAddServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftAddServer'
type MockManagerServiceClient_RaftAddServer_Call struct {
	*mock.Call
}

// RaftAddServer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.RaftAddServerRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) RaftAddServer(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_RaftAddServer_Call {
	return &MockManagerServiceClient_RaftAddServer_Call{Call: _e.mock.On("RaftAddServer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_RaftAddServer_Call) Run(run func(ctx context.Context, in *manager_pb.RaftAddServerRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_RaftAddServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.RaftAddServerRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.RaftAddServerRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_RaftAddServer_Call) Return(raftAddServerResponse *manager_pb.RaftAddServerResponse, err error) *MockManagerServiceClient_RaftAddServer_Call {
	_c.Call.Return(raftAddServerResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_RaftAddServer_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.RaftAddServerRequest, opts ...grpc.CallOption) (*manager_pb.RaftAddServerResponse, error)) *MockManagerServiceClient_RaftAddServer_Call {
	_c.Call.Return(run)
	return _c
}

// RaftListClusterServers provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) RaftListClusterServers(ctx context.Context, in *manager_pb.RaftListClusterServersRequest, opts ...grpc.CallOption) (*manager_pb.RaftListClusterServersResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RaftListClusterServers")
	}

	var r0 *manager_pb.RaftListClusterServersResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftListClusterServersRequest, ...grpc.CallOption) (*manager_pb.RaftListClusterServersResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftListClusterServersRequest, ...grpc.CallOption) *manager_pb.RaftListClusterServersResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.RaftListClusterServersResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.RaftListClusterServersRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_RaftListClusterServers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftListClusterServers'
type MockManagerServiceClient_RaftListClusterServers_Call struct {
	*mock.Call
}

// RaftListClusterServers is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.RaftListClusterServersRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) RaftListClusterServers(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_RaftListClusterServers_Call {
	return &MockManagerServiceClient_RaftListClusterServers_Call{Call: _e.mock.On("RaftListClusterServers",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_RaftListClusterServers_Call) Run(run func(ctx context.Context, in *manager_pb.RaftListClusterServersRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_RaftListClusterServers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.RaftListClusterServersRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.RaftListClusterServersRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_RaftListClusterServers_Call) Return(raftListClusterServersResponse *manager_pb.RaftListClusterServersResponse, err error) *MockManagerServiceClient_RaftListClusterServers_Call {
	_c.Call.Return(raftListClusterServersResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_RaftListClusterServers_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.RaftListClusterServersRequest, opts ...grpc.CallOption) (*manager_pb.RaftListClusterServersResponse, error)) *MockManagerServiceClient_RaftListClusterServers_Call {
	_c.Call.Return(run)
	return _c
}

// RaftRemoveServer provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) RaftRemoveServer(ctx context.Context, in *manager_pb.RaftRemoveServerRequest, opts ...grpc.CallOption) (*manager_pb.RaftRemoveServerResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RaftRemoveServer")
	}

	var r0 *manager_pb.RaftRemoveServerResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftRemoveServerRequest, ...grpc.CallOption) (*manager_pb.RaftRemoveServerResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RaftRemoveServerRequest, ...grpc.CallOption) *manager_pb.RaftRemoveServerResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.RaftRemoveServerResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.RaftRemoveServerRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_RaftRemoveServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RaftRemoveServer'
type MockManagerServiceClient_RaftRemoveServer_Call struct {
	*mock.Call
}

// RaftRemoveServer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.RaftRemoveServerRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) RaftRemoveServer(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_RaftRemoveServer_Call {
	return &MockManagerServiceClient_RaftRemoveServer_Call{Call: _e.mock.On("RaftRemoveServer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_RaftRemoveServer_Call) Run(run func(ctx context.Context, in *manager_pb.RaftRemoveServerRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_RaftRemoveServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.RaftRemoveServerRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.RaftRemoveServerRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_RaftRemoveServer_Call) Return(raftRemoveServerResponse *manager_pb.RaftRemoveServerResponse, err error) *MockManagerServiceClient_RaftRemoveServer_Call {
	_c.Call.Return(raftRemoveServerResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_RaftRemoveServer_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.RaftRemoveServerRequest, opts ...grpc.CallOption) (*manager_pb.RaftRemoveServerResponse, error)) *MockManagerServiceClient_RaftRemoveServer_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterService provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) RegisterService(ctx context.Context, in *manager_pb.RegisterServiceRequest, opts ...grpc.CallOption) (*manager_pb.RegisterServiceResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterService")
	}

	var r0 *manager_pb.RegisterServiceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RegisterServiceRequest, ...grpc.CallOption) (*manager_pb.RegisterServiceResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.RegisterServiceRequest, ...grpc.CallOption) *manager_pb.RegisterServiceResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.RegisterServiceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.RegisterServiceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_RegisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterService'
type MockManagerServiceClient_RegisterService_Call struct {
	*mock.Call
}

// RegisterService is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.RegisterServiceRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) RegisterService(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_RegisterService_Call {
	return &MockManagerServiceClient_RegisterService_Call{Call: _e.mock.On("RegisterService",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_RegisterService_Call) Run(run func(ctx context.Context, in *manager_pb.RegisterServiceRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_RegisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.RegisterServiceRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.RegisterServiceRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_RegisterService_Call) Return(registerServiceResponse *manager_pb.RegisterServiceResponse, err error) *MockManagerServiceClient_RegisterService_Call {
	_c.Call.Return(registerServiceResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_RegisterService_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.RegisterServiceRequest, opts ...grpc.CallOption) (*manager_pb.RegisterServiceResponse, error)) *MockManagerServiceClient_RegisterService_Call {
	_c.Call.Return(run)
	return _c
}

// UnregisterService provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) UnregisterService(ctx context.Context, in *manager_pb.UnregisterServiceRequest, opts ...grpc.CallOption) (*manager_pb.UnregisterServiceResponse, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for UnregisterService")
	}

	var r0 *manager_pb.UnregisterServiceResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.UnregisterServiceRequest, ...grpc.CallOption) (*manager_pb.UnregisterServiceResponse, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.UnregisterServiceRequest, ...grpc.CallOption) *manager_pb.UnregisterServiceResponse); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*manager_pb.UnregisterServiceResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.UnregisterServiceRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_UnregisterService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnregisterService'
type MockManagerServiceClient_UnregisterService_Call struct {
	*mock.Call
}

// UnregisterService is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.UnregisterServiceRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) UnregisterService(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_UnregisterService_Call {
	return &MockManagerServiceClient_UnregisterService_Call{Call: _e.mock.On("UnregisterService",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_UnregisterService_Call) Run(run func(ctx context.Context, in *manager_pb.UnregisterServiceRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_UnregisterService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.UnregisterServiceRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.UnregisterServiceRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_UnregisterService_Call) Return(unregisterServiceResponse *manager_pb.UnregisterServiceResponse, err error) *MockManagerServiceClient_UnregisterService_Call {
	_c.Call.Return(unregisterServiceResponse, err)
	return _c
}

func (_c *MockManagerServiceClient_UnregisterService_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.UnregisterServiceRequest, opts ...grpc.CallOption) (*manager_pb.UnregisterServiceResponse, error)) *MockManagerServiceClient_UnregisterService_Call {
	_c.Call.Return(run)
	return _c
}

// WatchTopology provides a mock function for the type MockManagerServiceClient
func (_mock *MockManagerServiceClient) WatchTopology(ctx context.Context, in *manager_pb.WatchTopologyRequest, opts ...grpc.CallOption) (manager_pb.ManagerService_WatchTopologyClient, error) {
	// grpc.CallOption
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for WatchTopology")
	}

	var r0 manager_pb.ManagerService_WatchTopologyClient
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.WatchTopologyRequest, ...grpc.CallOption) (manager_pb.ManagerService_WatchTopologyClient, error)); ok {
		return returnFunc(ctx, in, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *manager_pb.WatchTopologyRequest, ...grpc.CallOption) manager_pb.ManagerService_WatchTopologyClient); ok {
		r0 = returnFunc(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(manager_pb.ManagerService_WatchTopologyClient)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *manager_pb.WatchTopologyRequest, ...grpc.CallOption) error); ok {
		r1 = returnFunc(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockManagerServiceClient_WatchTopology_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WatchTopology'
type MockManagerServiceClient_WatchTopology_Call struct {
	*mock.Call
}

// WatchTopology is a helper method to define mock.On call
//   - ctx context.Context
//   - in *manager_pb.WatchTopologyRequest
//   - opts ...grpc.CallOption
func (_e *MockManagerServiceClient_Expecter) WatchTopology(ctx interface{}, in interface{}, opts ...interface{}) *MockManagerServiceClient_WatchTopology_Call {
	return &MockManagerServiceClient_WatchTopology_Call{Call: _e.mock.On("WatchTopology",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockManagerServiceClient_WatchTopology_Call) Run(run func(ctx context.Context, in *manager_pb.WatchTopologyRequest, opts ...grpc.CallOption)) *MockManagerServiceClient_WatchTopology_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *manager_pb.WatchTopologyRequest
		if args[1] != nil {
			arg1 = args[1].(*manager_pb.WatchTopologyRequest)
		}
		var arg2 []grpc.CallOption
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockManagerServiceClient_WatchTopology_Call) Return(managerService_WatchTopologyClient manager_pb.ManagerService_WatchTopologyClient, err error) *MockManagerServiceClient_WatchTopology_Call {
	_c.Call.Return(managerService_WatchTopologyClient, err)
	return _c
}

func (_c *MockManagerServiceClient_WatchTopology_Call) RunAndReturn(run func(ctx context.Context, in *manager_pb.WatchTopologyRequest, opts ...grpc.CallOption) (manager_pb.ManagerService_WatchTopologyClient, error)) *MockManagerServiceClient_WatchTopology_Call {
	_c.Call.Return(run)
	return _c
}
